### PR TITLE
Shortcut icon

### LINKED ISSUE #1472: Shortcut not loading correct view after closing app using home button
**Home Assistant Android version:** beta-644-6e9ac72-full

**Android version:** 10 (EMUI 11.0.0)

**Phone model:** Huawei Mate 20 Pro

**Home Assistant version:** 2021.4.0b0

**Last working Home Assistant release (if known):**

**Description of problem:**

When opening a pinned or dynamic shortcut and then backing out of the app using the home button, opening a second shortcut will sometimes just open the app showing the last open view.

Have been able to reliably reproduce this by:
* Open Home Assistant app
* Close app with back button
* Opening first shortcut
* Back out of the app using the home button
* Open second shortcut
* Back out of the app using the home button
* Open first shortcut again

If the app is closed using the back button, the shortcuts work as expected.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

Screen recording of a minimal reproduction using two test shortcuts and views:

https://user-images.githubusercontent.com/2099542/113353169-306e0b00-9335-11eb-81aa-7a975b9daedb.mp4

(Updated screen recording using debug build of app and showing the closing of the HA app)

**Additional information:**

Using Nova Launcher, but also been able to reproduce using Huawei Home launcher.

### PR DESCRIPTION
**Pull request by dshokouhi**
## Summary

Let users select and use material icons for shortcut icons

Also fixes #1472 

## Screenshots

image

image

image

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

### CODE REVIEW

File: app/src/main/java/io/homeassistant/companion/android/util/NotificationActionContentHandler.kt [hunk 1]
```diff
@@ -25,6 +25,7 @@ object NotificationActionContentHandler {
             } ?: WebViewActivity.newInstance(context)
 
             intent.flags = Intent.FLAG_ACTIVITY_NEW_TASK
+            intent.flags = Intent.FLAG_ACTIVITY_MULTIPLE_TASK
```
Comment (JBassett) [inline app/src/main/java/io/homeassistant/companion/android/util/NotificationActionContentHandler.kt:28]: Doesn't the second line just override the first?

File: app/src/main/java/io/homeassistant/companion/android/settings/shortcuts/ManageShortcutsSettingsFragment.kt [hunk 2]
```diff
@@ -133,6 +157,14 @@ class ManageShortcutsSettingsFragment : PreferenceFragmentCompat() {
                 }
             }
 
+            findPreference<Preference>(SHORTCUT_PREFIX + i + ICON_PREFIX)?.let {
+                it.setOnPreferenceClickListener {
+                    LAST_ICON_SELECT = SHORTCUT_PREFIX + i
+                    iconDialog.show(childFragmentManager, ICON_DIALOG_TAG)
```
Comment (JBassett) [inline app/src/main/java/io/homeassistant/companion/android/settings/shortcuts/ManageShortcutsSettingsFragment.kt:163]:
```suggestion
                    iconDialog.show(childFragmentManager, SHORTCUT_PREFIX + i)
```

File: app/src/main/java/io/homeassistant/companion/android/settings/shortcuts/ManageShortcutsSettingsFragment.kt [hunk 3]
```diff
@@ -263,6 +295,14 @@ class ManageShortcutsSettingsFragment : PreferenceFragmentCompat() {
                 }
             }
 
+            findPreference<Preference>("pinned_shortcut_icon")?.let {
+                it.setOnPreferenceClickListener {
+                    LAST_ICON_SELECT = "pinned"
+                    iconDialog.show(childFragmentManager, ICON_DIALOG_TAG)
```
Comment (JBassett) [inline app/src/main/java/io/homeassistant/companion/android/settings/shortcuts/ManageShortcutsSettingsFragment.kt:301]:
```suggestion
                    iconDialog.show(childFragmentManager, "pinned")
```

File: app/src/main/java/io/homeassistant/companion/android/settings/shortcuts/ManageShortcutsSettingsFragment.kt [hunk 4]
```diff
@@ -355,4 +401,28 @@ class ManageShortcutsSettingsFragment : PreferenceFragmentCompat() {
...
+
+    override fun onIconDialogIconsSelected(dialog: IconDialog, icons: List<com.maltaisn.icondialog.data.Icon>) {
+        Log.d(TAG, "Selected icon: ${icons.firstOrNull()}")
+        val selectedIcon = icons.firstOrNull()
+        if (selectedIcon != null) {
+            val iconDrawable = selectedIcon.drawable
+            if (iconDrawable != null) {
+                val icon = DrawableCompat.wrap(iconDrawable)
+                icon.setColorFilter(resources.getColor(R.color.colorAccent), PorterDuff.Mode.SRC_IN)
+                when (LAST_ICON_SELECT) {
```
Comment (JBassett) [inline app/src/main/java/io/homeassistant/companion/android/settings/shortcuts/ManageShortcutsSettingsFragment.kt:416]:
```suggestion
                when (dialog.tag) {
```
I think this is the syntax....

**Review by JBassett — CHANGES_REQUESTED** [review]

File: app/src/main/java/io/homeassistant/companion/android/util/NotificationActionContentHandler.kt (hunk 1 above)
Comment (dshokouhi) [reply app/src/main/java/io/homeassistant/companion/android/util/NotificationActionContentHandler.kt:28]: It was to my understanding we needed both flags because it says its always paired with the original flag:

https://developer.android.com/reference/android/content/Intent#FLAG_ACTIVITY_MULTIPLE_TASK

Comment (dshokouhi) [reply app/src/main/java/io/homeassistant/companion/android/util/NotificationActionContentHandler.kt:28]: The real purpose I believe for the fix for #1472 is this comment

`Used in conjunction with FLAG_ACTIVITY_NEW_TASK to disable the behavior of bringing an existing task to the foreground.`

Comment (dshokouhi) [reply app/src/main/java/io/homeassistant/companion/android/util/NotificationActionContentHandler.kt:28]: oh wait, I see what you mean 🤦‍♂️ wrong syntax lol

**Review by JBassett — APPROVED** [review]
