### PR TITLE
Do not trigger sensors update on alarm and bluetooth events if the corresponding sensor is disabled

### LINKED ISSUE #869: Alarm sensor spam
**Home Assistant Android version:**
self-built based on beta-345-68b8987
**Android version:**
9
**Phone model:**
Motorola G7+
**Home Assistant version:**
0.114.4
**Last working Home Assistant release (if known):**

**Description of problem:**

I've setup the SIP client (namely, Groundwire) on my phone and it seems to cause massive update_sensor_states spam to Home Assistant.

I've digged through the logs to see that this SIP client is setting up alarms roughly every 30 seconds when the screen is off to send keep-alives and registrations to the SIP server.

This causes android.app.action.NEXT_ALARM_CLOCK_CHANGED receivers to trigger. This in turn causes all sensors updating and sending their state to Home Assistant. Every 30 seconds.

The log is below. I've redacted it for easier reading because the only changing data is next_alarm.

Disabling alarm sensor doesn't help. I've took a look at the code and it seems that the only way to get rid of spam is to either remove `<action android:name="android.app.action.NEXT_ALARM_CLOCK_CHANGED" />` from AndroidManifest.xml or add some filter to SensorReceiver.onReceive() function and the alarm sensor itself.

**Traceback (if applicable):**

```
2020-09-02 10:05:22 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:05:53.330Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:05:53 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599030353330'}}, <redacted>]
2020-09-02 10:05:52 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:06:12.517Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:06:12 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599030372517'}}, <redacted>]
2020-09-02 10:06:11 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:06:23.348Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:06:23 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599030383348'}}, <redacted>]
2020-09-02 10:06:22 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:06:36.540Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:06:36 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599030396540'}}, <redacted>]
2020-09-02 10:06:35 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:06:53.361Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:06:53 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599030413361'}}, <redacted>]
2020-09-02 10:06:52 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:07:23.377Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:07:23 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599030443377'}}, <redacted>]
2020-09-02 10:07:22 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:07:53.400Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:07:53 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599030473400'}}, <redacted>]
2020-09-02 10:07:22 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:07:53.400Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:07:53 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599030473400'}}, <redacted>]
2020-09-02 10:07:52 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:08:12.558Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:08:12 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599030492558'}}, <redacted>]
2020-09-02 10:08:11 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:08:23.414Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:08:23 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599030503414'}}, <redacted>]
2020-09-02 10:08:22 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:08:36.568Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:08:36 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599030516568'}}, <redacted>]
2020-09-02 10:08:35 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:08:53.423Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:08:53 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599030533423'}}, <redacted>]
2020-09-02 10:08:52 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:09:23.434Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:09:23 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599030563434'}}, <redacted>]
2020-09-02 10:08:52 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:09:23.434Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:09:23 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599030563434'}}, <redacted>]
2020-09-02 10:09:22 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:09:53.444Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:09:53 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599030593444'}}, <redacted>]
2020-09-02 10:09:52 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:10:12.587Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:10:12 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599030612587'}}, <redacted>]
2020-09-02 10:10:11 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:10:23.459Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:10:23 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599030623459'}}, <redacted>]
2020-09-02 10:10:22 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:10:36.600Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:10:36 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599030636600'}}, <redacted>]
2020-09-02 10:11:04 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:11:24.296Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:11:24 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599030684296'}}, <redacted>]
2020-09-02 10:11:10 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:11:24.296Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:11:24 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599030684296'}}, <redacted>]
2020-09-02 10:11:23 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:11:54.302Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:11:54 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599030714302'}}, <redacted>]
2020-09-02 10:11:23 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:11:54.302Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:11:54 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599030714302'}}, <redacted>]
2020-09-02 10:11:53 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:12:12.056Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:12:12 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599030732056'}}, <redacted>]
2020-09-02 10:12:11 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:12:24.324Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:12:24 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599030744324'}}, <redacted>]
2020-09-02 10:12:23 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:12:32.072Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:12:32 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599030752072'}}, <redacted>]
2020-09-02 10:12:31 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:12:54.333Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:12:54 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599030774333'}}, <redacted>]
2020-09-02 10:14:47 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:14:55.326Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:14:55 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599030895326'}}, <redacted>]
2020-09-02 10:14:54 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:15:25.339Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:15:25 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599030925339'}}, <redacted>]
2020-09-02 10:14:54 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:15:25.339Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:15:25 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599030925339'}}, <redacted>]
2020-09-02 10:15:39 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:15:43.053Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:15:43 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599030943053'}}, <redacted>]
2020-09-02 10:15:42 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:15:55.648Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:15:55 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599030955648'}}, <redacted>]
2020-09-02 10:15:55 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:16:25.653Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:16:25 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599030985653'}}, <redacted>]
2020-09-02 10:16:24 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:16:51.063Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:16:51 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599031011063'}}, <redacted>]
2020-09-02 10:16:50 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:16:55.670Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:16:55 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599031015670'}}, <redacted>]
2020-09-02 10:17:40 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:17:55.978Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:17:55 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599031075978'}}, <redacted>]
2020-09-02 10:17:40 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:17:55.978Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:17:55 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599031075978'}}, <redacted>]
2020-09-02 10:17:55 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:18:19.406Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:18:19 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599031099406'}}, <redacted>]
2020-09-02 10:18:18 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:18:26.302Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:18:26 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599031106302'}}, <redacted>]
2020-09-02 10:18:25 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:18:56.312Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:18:56 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599031136312'}}, <redacted>]
2020-09-02 10:18:25 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:18:56.312Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:18:56 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599031136312'}}, <redacted>]
2020-09-02 10:18:55 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:19:26.642Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:19:26 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599031166642'}}, <redacted>]
2020-09-02 10:19:34 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:19:50.735Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:19:50 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599031190735'}}, <redacted>]
2020-09-02 10:19:48 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:19:50.735Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:19:50 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599031190735'}}, <redacted>]
2020-09-02 10:19:49 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:19:56.993Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:19:56 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599031196993'}}, <redacted>]
2020-09-02 10:19:56 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:20:26.998Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:20:26 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599031226998'}}, <redacted>]
2020-09-02 10:19:56 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:20:26.998Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:20:26 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599031226998'}}, <redacted>]
2020-09-02 10:20:26 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:20:57.021Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:20:57 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599031257021'}}, <redacted>]
2020-09-02 10:20:56 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:21:19.740Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:21:19 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599031279740'}}, <redacted>]
2020-09-02 10:21:18 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:21:27.033Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:21:27 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599031287033'}}, <redacted>]
2020-09-02 10:21:34 DEBUG (MainThread) [homeassistant.components.mobile_app.webhook] Received webhook payload from Anna for type update_sensor_states: [<redacted>, {'unique_id': 'next_alarm', 'state': '2020-09-02T07:21:57.367Z', 'type': 'sensor', 'icon': 'mdi:alarm', 'attributes': {'Local Time': 'Wed Sep 02 10:21:57 GMT+03:00 2020', 'Package': 'Unknown', 'Time in Milliseconds': '1599031317367'}}, <redacted>]
```

**Screenshot of problem:**

**Additional information:**

### PR DESCRIPTION
**Pull request by anyuta1166**
Do not trigger sensors update on alarm and bluetooth events if the corresponding sensor is disabled

Partially fixes #869. I wanted to implement some kind of filter, but this is discussable. So here is the easiest solution to get rid of spam just by disabling the corresponding sensor ;-0

### CODE REVIEW

**Comment by dshokouhi** [comment]
Now that we have all sensors disabled by default I think we should use a solution that benefits all of the sensors instead of just one. For example why trigger a bluetooth update if the user does not have that enabled either. I do agree cutting down on the spam will be very helpful.

**Comment by dshokouhi** [comment]
I also wonder if maybe a better approach would be to ignore any update if none of the sensors have any update to send over to HA. That way we can continue to send updates to other sensors who have an update.  This would also allow us to register with `ACTION_BATTERY_CHANGED` to get better battery level reporting as we can then ignore the updates we don't care for.

**Comment by anyuta1166** [comment]
> For example why trigger a bluetooth update if the user does not have that enabled either.

I forgot about bluetooth sensor. It's listener is registered in AndroidManifest.xml too.

**Comment by dshokouhi** [comment]
Yea maybe we should just review what sends too many updates...for sure right now Next Alarm probably does the most out of any of them so we should consider that.  Lets see what comes up during the review process, sorry I didn't mean for you to change your code so quickly :) I thought we would all discuss whats the best way to do this first.  I have more planned receivers in the future too but they don't trigger like Next Alarm would.  Honestly the more I think about it the more next alarm sticks out like a sore thumb compared to the rest 🤔

**Comment by dshokouhi** [comment]
After looking at the other receivers I don't think any of them have the issue of spam so sorry I misspoke and gave bluetooth as an example.  This is the only receiver I can see that another app can abuse.  The only other exception to spam would be the one receiver I mentioned which is definitely out of scope here.

**Comment by anyuta1166** [comment]
Filtering out bluetooth events if the sensor is disabled looks logical too. Even though it's not prone to spam. Just because listener is registered in AndroidManifest.xml too and gets triggered even if the sensor is disabled,

**Review by dshokouhi — APPROVED** [review]
Tested out the changes, looks good from what I can see.

**Comment by anyuta1166** [comment]
Refactored the code and added bluetooth event which I missed.

File: app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt [hunk 1]
```diff
@@ -61,6 +62,27 @@ class SensorReceiver : BroadcastReceiver() {
...
+                val sensorDao = AppDatabase.getInstance(context).sensorDao()
+                val sensor = sensorDao.get(NextAlarmManager.nextAlarm.id)
+                if (sensor?.enabled != true) {
+                    Log.d(TAG, "Alarm Sensor disabled, skipping sensors update")
+                    return
+                }
+            }
+            "android.bluetooth.device.action.ACL_CONNECTED",
+                "android.bluetooth.device.action.ACL_DISCONNECTED",
+                BluetoothAdapter.ACTION_STATE_CHANGED -> {
```
Comment (dshokouhi) [inline app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt:76]: So now we are adding a registered receiver too? I was thinking here we would just skip the ones we can't get rid of and find a better way to skip the register/unregister as needed, otherwise we would need to take care of all the other receivers on this page and it may get a bit out of hand :)

Comment (anyuta1166) [reply app/src/main/java/io/homeassistant/companion/android/sensors/SensorReceiver.kt:76]: Just for consistency - to filter out all bluetooth events. It might be removed from here when a better way to skip the register/unregister as needed will be found.

**Review by JBassett — APPROVED** [review]
