### PR TITLE
Fix fire and forget resync to avoid blocking UI at startup

### LINKED ISSUE #5689: App takes a long time to open after update to 2025.8.7
UPDATE:
THIS BUG IS RELATED TO HAVING MORE THAN ONE SERVER IN THE APP. IF YOU ONLY HAVE ONE SERVER YOU MAY NOT HAVE A PROBLEM.

**Home Assistant Android app version(s):**
2025.8.7

**Android version(s):**
16
**Device model(s):**
Google Pixel 6 Pro
**Home Assistant version:**
2025.8.2
**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
On opening the app the loading spinning wheel is presented for anywhere from 10s to over 2m
This is a new behaviour since the app was updated from the play store two days ago. Prior to this the app opened almost instantly to my dashboard without any noticeable delay.
This is the same on WiFi at home where HA is installed, and away from Wifi on mobile.
It usually eventually loads, but the long delay is making it almost unusable.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

### PR DESCRIPTION
**Pull request by TimoPtr**
## Summary

In https://github.com/home-assistant/android/pull/5581 we've introduce a regression by making the `resyncRegistration` part of the flow. The regression is only visible when one server is not responding or any call during the registration. It was causing the start to be postpone until the server timeout (could be up to 30s).

 This PR does move the registration back into a dedicated coroutine scope. This fix the slow delay issue but it does mean that the activity could out live it's lifecycle, which is bad but it is limited to maximum the timeout of the server so 30s.

## Checklist

- [ ] New or updated tests have been added to cover the changes following the testing [guidelines](https://developers.home-assistant.io/docs/android/testing/introduction).
- [ ] The code follows the project's [code style](https://developers.home-assistant.io/docs/android/codestyle) and [best_practices](https://developers.home-assistant.io/docs/android/best_practices).
- [x] The changes have been thoroughly tested, and edge cases have been considered.
- [x] Changes are backward compatible whenever feasible. Any breaking changes are documented in the changelog for users and/or in the code for developers depending on the relevance.

## Any other notes

Fixes #5689 

We could consider adding a new state to a server to mark it as disabled and avoid calling a server if we know that it might not respond. It might be useful for ppl that are managing servers for other and where they are not able to reach out to this server but they still want the server in the app for when they are able to reach out.

### CODE REVIEW

**Comment by TimoPtr** [comment]
We could consider moving this to a Worker in a second step.

**Comment by jpelgrom** [comment]
Couldn't the variable live in `LaunchPresenterBase` instead? Now you're duplicating a lot of lines.

Adjusted title because the intention was always that this action was a best effort sync but not blocking/"fire and forget".

> We could consider adding a new state to a server to mark it as disabled and avoid calling a server if we know that it might not respond. It might be useful for ppl that are managing servers for other and where they are not able to reach out to this server but they still want the server in the app for when they are able to reach out.
>
> We could consider moving this to a Worker in a second step.

I'm not in favour of adding more configuration like that to the app unless absolutely necessary. Just a silent failure which isn't blocking should be enough. A worker could be nice (there is even a comment that has existed for a long time asking if this is the right place, but it was never a priority or issue), but out of scope for this PR.

**Comment by TimoPtr** [comment]
> Couldn't the variable live in `LaunchPresenterBase` instead? Now you're duplicating a lot of lines.
> 
> Adjusted title because the intention was always that this action was a best effort sync but not blocking/"fire and forget".
> 
> > We could consider adding a new state to a server to mark it as disabled and avoid calling a server if we know that it might not respond. It might be useful for ppl that are managing servers for other and where they are not able to reach out to this server but they still want the server in the app for when they are able to reach out.
> > We could consider moving this to a Worker in a second step.
> 
> I'm not in favour of adding more configuration like that to the app unless absolutely necessary. Just a silent failure which isn't blocking should be enough. A worker could be nice (there is even a comment that has existed for a long time asking if this is the right place, but it was never a priority or issue), but out of scope for this PR.

Indeed it can I'm going to adjsut. Then I'm going to open an issue with the details 👍🏻

**Comment by TimoPtr** [comment]
https://github.com/home-assistant/android/issues/5724

File: app/src/main/kotlin/io/homeassistant/companion/android/launch/LaunchPresenterBase.kt [hunk 1]
```diff
@@ -17,6 +20,26 @@ abstract class LaunchPresenterBase(
...
+     * This is crucial for operations like server resynchronization, especially when dealing with
+     * multiple servers where one might be unresponsive.
+     *
+     * By launching tasks in this scope, we ensure that the UI remains responsive and is displayed
+     * promptly, even if a server connection times out.
+     *
+     * **Note:** Using a dedicated scope like this means that the underlying Activity might not be
+     * destroyed immediately if these background tasks are still running. This is a trade-off
+     * for improved UI responsiveness in scenarios with potential network delays. If we
+     * introduce a new server state like disable we could maybe bring this back in the flow.
```
Comment (jpelgrom) [inline app/src/main/kotlin/io/homeassistant/companion/android/launch/LaunchPresenterBase.kt]:
```suggestion
     * for improved UI responsiveness in scenarios with potential network delays.
```

Considering the other adjusted comment and how we need to keep the app launch as fast as possible, I don't think we ever want to have this blocking the flow, so remove the line?

Comment (TimoPtr) [reply app/src/main/kotlin/io/homeassistant/companion/android/launch/LaunchPresenterBase.kt]: Done
