### PR TITLE
Fix Storage sensors to update continuously and display correct size unit

### LINKED ISSUE #2637: Internal Storage sensor only updating once on app start
**Home Assistant Android version:** beta-2422-766e879d-full

**Android version:** 12

**Phone model:** S20FE 5G, S21 5G

**Home Assistant version:** 2022.6.6

**Last working Home Assistant release (if known):** Judging based on the code, it's been like this since the feature's introduction.

**Description of problem:** The Internal Storage sensor should be updated regularly. Instead, it's only updated on app start, because the values are stored in a `companion object` of `StorageSensorManager`, and only calculated once when the `companion object` is being initialized.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:** 

**Additional information:**

### PR DESCRIPTION
**Pull request by marazmarci**
Fixes #2637 

## Summary

The state of the Internal Storage sensor was stored in the `companion object` of `StorageSensorManager`. It was calculated once when the `companion object` was initialized. I fixed it and also did some refactoring.

Based on the code, the Free and the Total attributes' unit was supposed to be dynamic (KB / MB / GB), but it always displayed GB because the logic was flawed. Now it can not only output 0GB for smaller values (<1GB) but also 345MB or 640KB for example.

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

## Any other notes

This app may come in handy for testing this:
[Fill Storage – Google Play](https://play.google.com/store/apps/details?id=com.arumcomm.fillstorage)

### CODE REVIEW

**Comment by jpelgrom** [comment]
Please don't change the line endings from `CRLF` to `LF`, Git will consider all lines to have changed (as you can also see on GitHub) which results in a messy history

**Comment by marazmarci** [comment]
@jpelgrom I changed the line endings back to `CRLF`.

File: app/src/main/java/io/homeassistant/companion/android/sensors/StorageSensorManager.kt [hunk 1]
```diff
@@ -113,29 +104,19 @@ class StorageSensorManager : SensorManager {
...
             context,
             externalStorage,
-            percentFreeExternal,
+            externalStorageStats?.percentage ?: 0,
             externalStorage.statelessIcon,
             mapOf(
-                "free_external_storage" to freeExternalStorage,
-                "total_external_storage" to totalExternalStorage
+                "free_external_storage" to (externalStorageStats?.freeBytes ?: "No SD Card"),
+                "total_external_storage" to (externalStorageStats?.totalBytes ?: "No SD Card")
```
Comment (marazmarci) [inline app/src/main/java/io/homeassistant/companion/android/sensors/StorageSensorManager.kt:119]: Off-topic:
These attribute names don't match the ones written in the [documentation](https://companion.home-assistant.io/docs/core/sensors/#storage-sensor)

Comment (dshokouhi) [reply app/src/main/java/io/homeassistant/companion/android/sensors/StorageSensorManager.kt:119]: We should update the documentation then, I thought we had updated this a while back but may have missed the documentation. Attribute names should be all lower case with underscores for best HA core compatibility. There may or may not be other places to correct now :)

File: app/src/main/java/io/homeassistant/companion/android/sensors/StorageSensorManager.kt [hunk 2]
```diff
@@ -125,29 +125,21 @@ class StorageSensorManager : SensorManager {
...
-        var commaOffset = resultBuffer.length - 3
-        while (commaOffset > 0) {
-            resultBuffer.insert(commaOffset, ',')
-            commaOffset -= 3
-        }
-
-        resultBuffer.append(suffix)
-        return resultBuffer.toString()
+        val sizeWithThousandsSeparator = String.format("%,d", sizeLong)
+        return "$sizeWithThousandsSeparator$suffix"
```
Comment (marazmarci) [inline app/src/main/java/io/homeassistant/companion/android/sensors/StorageSensorManager.kt:142]: I just found that this method needs some improvement, but it isn't strictly related to this PR's scope.

Is it OK to have them in this PR or should I create a new PR for them?

Comment (jpelgrom) [reply app/src/main/java/io/homeassistant/companion/android/sensors/StorageSensorManager.kt:142]: I think it's fine to update the scope from "fix updating the storage sensors" to "fix the storage sensors", strictly speaking refactoring is already out of scope 😉

**Comment by marazmarci** [comment]
I edited the PR's name and description and also reworded the commit message of 1f9e57f8 (new: 6980a2e9).

File: app/src/main/java/io/homeassistant/companion/android/sensors/StorageSensorManager.kt (hunk 2 above)
Comment (marazmarci) [reply app/src/main/java/io/homeassistant/companion/android/sensors/StorageSensorManager.kt:142]: I edited the PR's name and description (and also reworded the commit message of 1f9e57f8 → new: 6980a2e9)

**Review by JBassett — APPROVED** [review]
