### PR TITLE
Skip car intent for car_ui notifications on non-Automotive minimal flavor

### LINKED ISSUE #6676: Minimal app version crashes when a server notificaton is received from the server
**Home Assistant Android app version(s):**
2026.3.2  (app-minimal-release.apk)
**Android version(s):**
16
**Device model(s):**
Pixel (without google services)
**Home Assistant version:**
2026.4.1
**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**
When a notification arrives in the app, it suddenly stops and sometimes displays the error message shown below.

**Companion App Logs:**

```
type: crash
flags: dev options enabled 
package: io.homeassistant.companion.android.minimal:20802, targetSdk 36 
process: io.homeassistant.companion.android.minimal 
processUptime: 27644 + 342 ms 

java.security.InvalidParameterException: Intent does not have the CarAppService's ComponentName as its targetIntent { act=android.intent.action.VIEW cmp=io.homeassistant.companion.android.minimal/io.homeassistant.companion.android.vehicle.HaCarAppService } 
at androidx.car.app.notification.CarPendingIntent.validateIntent(CarPendingIntent.java:133) 
at androidx.car.app.notification.CarPendingIntent.getCarApp(CarPendingIntent.java:104) 
at io.homeassistant.companion.android.notifications.MessagingManager.handleCarUiVisible(MessagingManager.kt:1182) 
at io.homeassistant.companion.android.notifications.MessagingManager.sendNotification(MessagingManager.kt:1080) 
at io.homeassistant.companion.android.notifications.MessagingManager.access$sendNotification(MessagingManager.kt:113) 
at io.homeassistant.companion.android.notifications.MessagingManager$sendNotification$1.invokeSuspend(Unknown Source:15) 
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34) 
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100) 
at android.os.Handler.handleCallback(Handler.java:1070) 
at android.os.Handler.dispatchMessage(Handler.java:125) 
at android.os.Looper.dispatchMessage(Looper.java:333) 
at android.os.Looper.loopOnce(Looper.java:263) 
at android.os.Looper.loop(Looper.java:367) 
at android.app.ActivityThread.main(ActivityThread.java:9331) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:566) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837) Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@ff16bdc, Dispatchers.Main]
```

**Screenshot or video of problem:**

**Additional information:**

### PR DESCRIPTION
**Pull request by jpelgrom**
## Summary

Fix #6676 by not providing an intent to the app's car service when using the minimal flavor on a non-Automotive device.

 - The _service_ exists, but it's not referenced in the manifest as you need the UI library. The available UIs are for Automotive (full and minimal support) or projected (= Android Auto, full only).
 - The _extender_ is still set, as you might want phone notifications showing in a car interface when using the minimal app.

(I suppose we could include the projected library with minimal, as the library is open source, but Android Auto itself is closed source and there are no open source projection apps AFAIK. It makes little sense why we would bundle something that can only be used with closed source in a flavor trying to be 100% open source.)

## Checklist

- [ ] New or updated tests have been added to cover the changes following the testing [guidelines](https://developers.home-assistant.io/docs/android/testing/introduction).
- [x] The code follows the project's [code style](https://developers.home-assistant.io/docs/android/codestyle) and [best_practices](https://developers.home-assistant.io/docs/android/best_practices).
- [x] The changes have been thoroughly tested, and edge cases have been considered.
- [x] Changes are backward compatible whenever feasible. Any breaking changes are documented in the changelog for users and/or in the code for developers depending on the relevance.

## Screenshots

n/a

## Link to pull request in documentation repositories
I don't think this very specific exception needs documenting.

### CODE REVIEW

File: app/src/main/kotlin/io/homeassistant/companion/android/notifications/MessagingManager.kt [hunk 1]
```diff
@@ -1173,21 +1175,21 @@ class MessagingManager @Inject constructor(
...
-                        CarPendingIntent.getCarApp(
-                            context,
-                            carIntent.hashCode(),
-                            carIntent,
-                            PendingIntent.FLAG_IMMUTABLE,
-                        ),
-                    )
-                    .build(),
-            )
+            builder.extend(carExtender.build())
```
Comment (TimoPtr) [inline app/src/main/kotlin/io/homeassistant/companion/android/notifications/MessagingManager.kt:1192]: Do we want to even extend when we are not in full or automotive? What is the result of an empty extender?

Comment (jpelgrom) [reply app/src/main/kotlin/io/homeassistant/companion/android/notifications/MessagingManager.kt:1192]: It's needed to add an empty extender to show at all, see the [class description](https://developer.android.com/reference/kotlin/androidx/car/app/notification/CarAppExtender):

> However, notifications only show up in the car screen if it is extended with `CarAppExtender`, even if the extender does not override any properties. 

I believd it's still relevant for connecting a phone with the minimal app to an Android Automotive car, or if someone has another projected interface in the future.

**Review by TimoPtr — APPROVED** [review]
