### PR TITLE
Make Entity state parsing safer

### LINKED ISSUE #6454: Crash when loading android auto favorites from settings
**Home Assistant Android app version(s):**

2026.2.4-full

**Android version(s):**

16

**Device model(s):**

Pixel 10 Pro XL

**Home Assistant version:**

2026.2.x

**Last working Home Assistant release (if known):**

n/a

**Description of problem, include YAML if issue is related to notifications:**

Simply loading android auto favorites screen causes the following crash

**Companion App Logs:**

```
Timestamp: 2026-02-17 09:56:52.423
Thread: main
Exception: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at io.homeassistant.companion.android.common.data.integration.EntityKt.getIcon(Entity.kt:383)
	at io.homeassistant.companion.android.util.compose.entity.EntityPickerItem$Companion.from(EntityPicker.kt:157)
	at io.homeassistant.companion.android.util.compose.entity.EntityPickerKt$EntityPicker$1$1$1.invokeSuspend(EntityPicker.kt:206)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:829)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@d140ab9, androidx.compose.runtime.BroadcastFrameClock@e31efe, androidx.compose.runtime.LaunchedEffectImpl@9a46505, StandaloneCoroutine{Cancelling}@a99c65f, AndroidUiDispatcher@a6498ac]
```

**Screenshot or video of problem:**

Image

**Additional information:**

### PR DESCRIPTION
**Pull request by TimoPtr**
## Summary

Fixes #6454 caused by a custom integration that has a state attributes not a string. This PR goes a little further to avoid future issue coming from custom integrations. The idea is to warn with all the needed details and fallback to an empty state so that users can open the logs and see issue (and the associated `entity_id`) and report it to the maintainer. 

## Checklist

- [x] New or updated tests have been added to cover the changes following the testing [guidelines](https://developers.home-assistant.io/docs/android/testing/introduction).
- [x] The code follows the project's [code style](https://developers.home-assistant.io/docs/android/codestyle) and [best_practices](https://developers.home-assistant.io/docs/android/best_practices).
- [x] The changes have been thoroughly tested, and edge cases have been considered.
- [x] Changes are backward compatible whenever feasible. Any breaking changes are documented in the changelog for users and/or in the code for developers depending on the relevance.

## Any other notes

KTlint did some changes in `Entity` that I have been ignoring for a long time but I think it is fine to add it to this PR.

### CODE REVIEW

**Comment by TimoPtr** [comment]
@bgoncal you might be interested

File: common/src/main/kotlin/io/homeassistant/companion/android/common/data/integration/Entity.kt [hunk 1]
```diff
@@ -136,13 +221,24 @@ fun Entity.applyCompressedStateDiff(diff: CompressedStateDiff): Entity {
...
+        )
+    } else {
+        Entity(
+            entityId = entityId,
+            state = state,
+            attributes = newAttributes,
+            lastChanged = newLastChanged,
+            lastUpdated = newLastUpdated,
+        )
+    }
```
Comment (jpelgrom) [inline common/src/main/kotlin/io/homeassistant/companion/android/common/data/integration/Entity.kt:241]: If you want to pull the logic out OK, but I don't see why it needs to duplicate creating the entity. You might miss making a change in both places.

```suggestion
    val newState = plus?.state
    return Entity(
        entityId = entityId,
        state = newState ?: state,
        attributes = newAttributes,
        lastChanged = newLastChanged,
        lastUpdated = newLastUpdated,
    )
```

File: common/src/main/kotlin/io/homeassistant/companion/android/common/data/integration/Entity.kt [hunk 2]
```diff
@@ -23,21 +23,105 @@ import java.time.format.DateTimeFormatter
...
+ * Validates a JSON element representing an entity state. Returns the string content if valid,
+ * empty string if null, or empty string with a warning if the type is not a string.
+ */
+private fun validateStateElement(element: JsonElement, entityId: String): String =
+    when (element) {
+        is JsonPrimitive if element.isString -> element.content
+        is JsonNull -> ""
+        else -> {
+            Timber.w(
+                "Entity $entityId state is not a String: $element. Please open an issue on the relevant integration",
```
Comment (jpelgrom) [inline common/src/main/kotlin/io/homeassistant/companion/android/common/data/integration/Entity.kt]:
```suggestion
                "Entity $entityId state is not a String: $element. Please open an issue on the relevant integration.",
```

File: common/src/main/kotlin/io/homeassistant/companion/android/common/data/integration/Entity.kt [hunk 3]
```diff
@@ -380,7 +476,13 @@ fun Entity.getIcon(context: Context): IIcon {
          * Note: for SimplifiedEntity sometimes return a more general icon because we don't have state.
          */
         val compareState =
-            state.ifBlank { attributes["state"] as String? }
+            state.ifBlank {
+                val attributeState = attributes["state"]
+                if (attributeState != null && attributeState !is String) {
+                    Timber.w("Entity $entityId has non-String state attribute: ${attributeState::class.simpleName}. This is wrong please open an issue on the relevant integration.")
```
Comment (jpelgrom) [inline common/src/main/kotlin/io/homeassistant/companion/android/common/data/integration/Entity.kt]: Align the warning message for both states

```suggestion
                    Timber.w("Entity $entityId has non-String state attribute: ${attributeState::class.simpleName}. Please open an issue on the relevant integration.)
```

File: common/src/test/kotlin/io/homeassistant/companion/android/common/data/integration/EntityTest.kt [hunk 4]
```diff
@@ -52,6 +60,72 @@ class EntityTest {
...
+            val json = kotlinJsonMapper.encodeToString(entity)
+            val deserialized = kotlinJsonMapper.decodeFromString<Entity>(json)
+            assertEquals("unavailable", deserialized.state)
+        }
+    }
+
+    @Nested
+    inner class GetIcon {
+        @Test
+        fun `Given blank state and non-string state attribute when getting icon then does not crash`() {
```
Comment (jpelgrom) [inline common/src/test/kotlin/io/homeassistant/companion/android/common/data/integration/EntityTest.kt]:
```suggestion
        fun `Given blank state and non-string state attribute when getting icon then does not throw`() {
```

File: common/src/main/kotlin/io/homeassistant/companion/android/common/data/integration/Entity.kt (hunk 1 above)
Comment (TimoPtr) [reply common/src/main/kotlin/io/homeassistant/companion/android/common/data/integration/Entity.kt:241]: The state and news state are not of the same type. One is a String the other a JsonElement

Comment (jpelgrom) [reply common/src/main/kotlin/io/homeassistant/companion/android/common/data/integration/Entity.kt:241]: 🤦 Had the code opened and tested, but didn't check the suggestion in the IDE which would've flagged the subtly different constructor

Comment (TimoPtr) [reply common/src/main/kotlin/io/homeassistant/companion/android/common/data/integration/Entity.kt:241]: Funny I've made the same mistake when I self review, I didn't remember why I duplicated it...

**Comment by dshokouhi** [comment]
Tested debug APK locally and the issue is no longer there on my server, still not sure what entity caused it lol

**Review by jpelgrom — APPROVED** [review]
