### PR TITLE
Better guard against invalid `mdi` in entity icon

### LINKED ISSUE #6657: App crashes when trying to add Android Auto Favorites
**Home Assistant Android app version(s):** 2026.3.2-full

**Android version(s):** 16 (custom rom)

**Device model(s):** Oneplus 7T Pro

**Home Assistant version:** 2026.3.3

**Last working Home Assistant release (if known):** Not sure, but about a year ago it worked. (I also had fewer entities back then, so maybe not related to versions)

**Description of problem, include YAML if issue is related to notifications:**
Under Settings/Companion app, opening Android Auto favorites menu instantly crashes the app. I've tried on multiple phones (Samsung, Oneplus), with multiple OS versions (stock os, phones with custom roms), same thing happens with this particular HA server, because this only happens with one of my HA servers, if I activate the other one in the companion app, it works as expected. Also tried starting fresh with the app, and only adding the server with this problem, but no luck with that either. I've seen a very similar issue (https://github.com/home-assistant/android/issues/3770) but in my case the quick setting tiles work properly. Also, I don't think I have an excessive ammount of entities on the server that produces this issue (~3800), although the server that works has fewer entities (~1500). I attatched full logs of the system besides the relevant part of the companion app logs, (same exception can be observed) maybe it could help, but if you need anything else, let me know. 

[2026-03-30-11-31-43.log](https://github.com/user-attachments/files/26349285/2026-03-30-11-31-43.log)

**Companion App Logs:**

```
Timestamp: 2026-03-30 11:31:48.971
Thread: main
Exception: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.Collections$SingletonList.get(Collections.java:5260)
	at io.homeassistant.companion.android.common.data.integration.EntityKt.getIcon(Entity.kt:470)
	at io.homeassistant.companion.android.util.compose.entity.EntityPickerItem$Companion.from(EntityPicker.kt:157)
	at io.homeassistant.companion.android.util.compose.entity.EntityPickerKt$EntityPicker$1$1$1.invokeSuspend(EntityPicker.kt:206)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:829)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@78acba9, androidx.compose.runtime.BroadcastFrameClock@ddc652e, androidx.compose.runtime.LaunchedEffectImpl@d37f62c, StandaloneCoroutine{Cancelling}@d3f48cf, AndroidUiDispatcher@b3b425c]
```

**Screenshot or video of problem:** Can't attatch screen capture, so here's a link to it: https://cloud.zalkatibi.com/s/ALC2eNHHCSbpiMC

**Additional information:**

### PR DESCRIPTION
**Pull request by jpelgrom**
## Summary

Fixes #6657 by:
 - Only checking for MDI icons if the string actually has the `:` used to split
 - Using a default blank value if the icon attribute is `mdi:` (no item at index 1) so the fallback icon is returned

## Checklist

- [x] New or updated tests have been added to cover the changes following the testing [guidelines](https://developers.home-assistant.io/docs/android/testing/introduction).
- [x] The code follows the project's [code style](https://developers.home-assistant.io/docs/android/codestyle) and [best_practices](https://developers.home-assistant.io/docs/android/best_practices).
- [x] The changes have been thoroughly tested, and edge cases have been considered.
- [x] Changes are backward compatible whenever feasible. Any breaking changes are documented in the changelog for users and/or in the code for developers depending on the relevance.

## Screenshots

n/a

## Link to pull request in documentation repositories
n/a

### CODE REVIEW

File: common/src/main/kotlin/io/homeassistant/companion/android/common/data/integration/Entity.kt [hunk 1]
```diff
@@ -466,9 +466,9 @@ fun Entity.getVolumeStep(): Float {
 fun Entity.getIcon(context: Context): IIcon {
     val attributes = this.attributes
     val icon = attributes["icon"] as? String
-    return if (icon?.startsWith("mdi") == true) {
-        val mdiIcon = icon.split(":")[1]
-        return IconicsDrawable(context, "cmd-$mdiIcon").icon ?: Icon.cmd_bookmark
+    return if (icon?.startsWith("mdi:") == true) {
+        val mdiIcon = icon.split(":").getOrElse(1, { _ -> "" })
+        IconicsDrawable(context, "cmd-$mdiIcon").icon ?: Icon.cmd_bookmark
```
Comment (TimoPtr) [inline common/src/main/kotlin/io/homeassistant/companion/android/common/data/integration/Entity.kt:471]: What happens when mdiIcon is blank?

File: common/src/test/kotlin/io/homeassistant/companion/android/common/data/integration/EntityTest.kt [hunk 2]
```diff
@@ -124,6 +125,30 @@ class EntityTest {
...
+                entityId = "sensor.test",
+                state = "42",
+                attributes = mapOf("icon" to "mdi:abcdefgh"),
+            )
+            val icon = entity.getIcon(context)
+            assertEquals(Icon.cmd_bookmark, icon)
+        }
+
+        @Test
+        fun `Given custom non-mdi icon attribute attribute when getting icon then returns domain default`() {
```
[the remark this answers is not in the document]
Comment (TimoPtr) [reply common/src/test/kotlin/io/homeassistant/companion/android/common/data/integration/EntityTest.kt]: This is a valid comment.

File: common/src/main/kotlin/io/homeassistant/companion/android/common/data/integration/Entity.kt (hunk 1 above)
Comment (jpelgrom) [reply common/src/main/kotlin/io/homeassistant/companion/android/common/data/integration/Entity.kt:471]: If the string doesn't match a known icon, `IconicsDrawable` will return `null` which is why the `?:` exists

Comment (jpelgrom) [reply common/src/main/kotlin/io/homeassistant/companion/android/common/data/integration/Entity.kt:471]: I've edited the test to make this behavior more obvious as intentional. Let me know if this answers your question.

Comment (TimoPtr) [reply common/src/main/kotlin/io/homeassistant/companion/android/common/data/integration/Entity.kt:471]: All good 👍 thanks we can merge
