### PR TITLE
Restart location updates if we detect too much time passed since last update

### LINKED ISSUE #2681: Android App Stops Sending High Accuracy Location Updates
**Home Assistant Android version:** 2022.6.0-full

**Android version:** 12

**Phone model:** Pixel 4 XL

**Home Assistant version:** 2022.5.5 (Core)

**Last working Home Assistant release (if known):** 2022.5.5 (Core)

**Description of problem:**

With High Accuracy mode enabled for location updates, the HA app at some point stops sending location updates (and accessing location) at the expected frequency (every 5 seconds). I can reproduce this reliably by doing the following:

- Enable High Accuracy mode
- Observe throughout the day that the Android location access icon ([this](https://community-assets.home-assistant.io/original/4X/c/3/b/c3b830ab8fb379f61213edf2ac78955b0f032bc2.png)) is persistent, and location updates are being sent every 5s.
- Go to bed.
- In the morning, the location access icon is gone, and high accuracy location updates are no longer being sent, even though High Accuracy mode is still enabled and the persistent notification for it is present. This continues until High Accuracy Mode is disabled and then re-enabled in the app.

I have already done the following to troubleshoot this:

- https://companion.home-assistant.io/docs/troubleshooting/faqs/#device-tracker-is-not-updating-in-android-app
- https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app
- Disabled "Include in Sensor Updates" for the Single Accurate Location sensor ([on advice from dshokouhi](https://community.home-assistant.io/t/location-updating-doesnt-work-very-serious-problem-for-my-automations/437206/14?u=rockduster))
- Tested the full debug APK from [this fix](https://github.com/home-assistant/android/actions/runs/2664693284), and confirmed the same behavior.

Zone based location updates still appear to function when the app has got into this state, but no other location updates do.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

Here are some app logs. I pulled these when I woke up and found that location updates had stopped, before disabling/re-enabling High Accuracy mode to fix it: [Logs](https://github.com/home-assistant/android/files/9122815/ha.app.logs.txt)

I've also been discussing this with dshokouhi in [this thread](https://community.home-assistant.io/t/location-updating-doesnt-work-very-serious-problem-for-my-automations/437206), who asked me to file this bug.

### LINKED ISSUE #2720: Location tracking Problems in Beta Version
**Home Assistant Android version:**
Beta Version from 28.07.2022
**Android version:**
13
**Phone model:**
Pixel 5
**Home Assistant version:**
Home Assistant 2022.7.7
**Last working Home Assistant release (if known):**

**Description of problem:**
I use my phone to track if I (Person) am at home or not. Using "home" or "not_home".
Today I realised that something isn't working anymore. And I saw that my Phone isn't updating anymore.
After I quit my beta subscription of the android app and reinstalled the app, the problem was gone.
Before that I checked if the app had the permission to track my location, which it had.

You can see a Screenshot of my History of the past few days. On July 26th I left my home like they days before, but HA didn't noticed it anymore. Since then, the status was "home" until I changed to the non-beta version some minutes ago. So I think it is right to mention this problem before it will be released to the app in Playstore.
**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**
image

**Additional information:**

### PR DESCRIPTION
**Pull request by dshokouhi**
## Summary

Should hopefully fix #2681 and fix #2720 by evaluating how much time has passed since `lastLocationReceived`. If background location updates are supposed to be on we will check `lastLocationReceived` with the addition of double the max wait time. If high accuracy mode is on we will double the amount of time for the defined interval. If we detect too much time has passed we will stop services and start them again shortly thereafter.

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

### CODE REVIEW

File: app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt [hunk 1]
```diff
@@ -328,6 +348,7 @@ class LocationSensorManager : LocationSensorManagerBase() {
     }
 
     private fun stopHighAccuracyService() {
+        isBackgroundLocationSetup = false
```
Comment (jpelgrom) [inline app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt:351]: Won't this create problems when this function is called from [here](https://github.com/home-assistant/android/blob/90a9a27e5e371445f75481e7a93609528357d3ff/app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt#L271)? `requestLocationUpdates()`, which is called in the next line, doesn't set it back to `true`.

File: app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt [hunk 2]
```diff
@@ -504,6 +525,7 @@ class LocationSensorManager : LocationSensorManagerBase() {
     }
 
     private fun removeBackgroundUpdateRequests() {
+        isBackgroundLocationSetup = false
```
Comment (jpelgrom) [inline app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt:528]: Won't this create problems when this function is called from [here](https://github.com/home-assistant/android/blob/90a9a27e5e371445f75481e7a93609528357d3ff/app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt#L266)? `startHighAccuracyService(int)`, which is called in the next line, doesn't set it back to `true`.

File: app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt [hunk 3]
```diff
@@ -227,6 +232,21 @@ class LocationSensorManager : LocationSensorManagerBase() {
...
+                    ((lastLocationReceived + (DEFAULT_LOCATION_MAX_WAIT_TIME * 2L)) < now)
+                ) {
+                    Log.d(TAG, "Background location updates appear to have stopped, restarting location updates")
+                    removeBackgroundUpdateRequests()
+                } else if (
+                    highAccuracyModeEnabled &&
+                    ((lastLocationReceived + (getHighAccuracyModeUpdateInterval().toLong() * 2000L)) < now)
+                ) {
+                    Log.d(TAG, "High accuracy mode appears to have stopped, restarting high accuracy mode")
+                    stopHighAccuracyService()
```
Comment (jpelgrom) [inline app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt:247]: Why use stop + start it later instead of using the restart function?

File: app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt (hunk 1 above)
Comment (dshokouhi) [reply app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt:351]: it should not because it will only hit this part of the condition, thats why I changed it : 

https://github.com/home-assistant/android/blob/90a9a27e5e371445f75481e7a93609528357d3ff/app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt#L249-L255

File: app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt (hunk 2 above)
Comment (dshokouhi) [reply app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt:528]: It should actually hit this part first

https://github.com/home-assistant/android/blob/90a9a27e5e371445f75481e7a93609528357d3ff/app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt#L249-L255

File: app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt (hunk 3 above)
Comment (dshokouhi) [reply app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt:247]: because the next line we resetup background updates from the beginning again and re-evaluate everything

**Comment by dshokouhi** [comment]
So FWIW during testing originally I was going by `lastLocationSend` the issue with that is when we are using background location updates we also don't send updates if location has not changed in 15 minutes. That actually caused the code restart every 15 minutes so I came to know the code was working fine there. For High accuracy mode, the same thing should apply.  In these cases the assumption is that updates were working in the background and then suddenly stopped coming in so we detect if we should restart things. 

In cases where the app is killed all local variables used will revert back to default triggering the whole process to restart.

File: app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt (hunk 1 above)
Comment (jpelgrom) [reply app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt:351]: How would it end up in `setupBackgroundLocation` again? We cannot rely on when the SensorWorker starts.

File: app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt (hunk 2 above)
Comment (jpelgrom) [reply app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt:528]: How would it end up in `setupBackgroundLocation` again? It isn't called from this function or the code where I linked to.

File: app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt (hunk 1 above)
Comment (dshokouhi) [reply app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt:351]: Because after this condition, the next line hits `setupBackgroundLocation` as part of the same method `setupLocationTracking`

https://github.com/home-assistant/android/blob/fc7c6b8316d4ecc30fd640e3df5f5dc9b87ccdc1/app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt#L235-LL248

Immediately followed by: https://github.com/home-assistant/android/blob/fc7c6b8316d4ecc30fd640e3df5f5dc9b87ccdc1/app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt#L250

File: app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt (hunk 2 above)
Comment (dshokouhi) [reply app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt:528]: Its actually just after the time evaluation I added, as part of `setupLocationTracking`

File: app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt (hunk 1 above)
Comment (jpelgrom) [reply app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt:351]: I linked to `stopHighAccuracyService` from deeper inside `setupBackgroundLocation` when switching high accuracy mode from on -> off, so not in `setupLocationTracking` and after the "it will only hit this part of the condition" lines you linked to :)

File: app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt (hunk 2 above)
Comment (jpelgrom) [reply app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt:528]: I linked to `removeBackgroundUpdateRequests` from deeper inside `setupBackgroundLocation` when it is already setup and switching high accuracy mode from off -> on, so not in `setupLocationTracking` and after the "it should actually hit this part first" lines you linked to :)

Comment (dshokouhi) [reply app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt:528]: ok I see what you mean, will keep the variable logic within the condition :)

File: app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt (hunk 1 above)
Comment (dshokouhi) [reply app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt:351]: ok I see what you mean, will move the logic to be inside the condition. Thanks for further clarifying your first comment 🤦

Comment (jpelgrom) [reply app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt]: No problem and thanks for your patience, the code is complex and I easily could've missed something

Comment (dshokouhi) [reply app/src/full/java/io/homeassistant/companion/android/sensors/LocationSensorManager.kt]: Yea these changes are not easy, and things are easy to miss as a result.

**Review by JBassett — APPROVED** [review]
I saw we go for it, I want to get this into our next release which I hope to have next week if possible so It would be nice to get this in beta this week.
