### PR TITLE
Fix topbar being displayed in full screen in old API

### LINKED ISSUE #5539: Status Bar Still Visible in Fullscreen Mode
**Home Assistant Android app version(s):** 2025.6.6-minimal

**Android version(s):** Android 15 (Lenovo ZUI 17.0.138)

**Device model(s):** Lenovo M11 TB33FU

**Home Assistant version:** 2025.6.3

**Last working Home Assistant release (if known):** Unknown but this post with a different Lenovo model from earlier this year suggests 6+ months https://community.home-assistant.io/t/android-tablet-lenovo-p12-status-bar/827143/3

**Description of problem, include YAML if issue is related to notifications:**
The android status bar is still visible while in fullscreen mode (although missing icons) using the home assistant app on some Lenovo tablets. This behavior is not seen when using hermit browser to create a 'lite app' in fullscreen mode. This is not an issue on my Pixel 8 Pro so it must be related to tablets or the Lenovo ROM. 

**Companion App Logs:** N/A

**Screenshot or video of problem:**
HA App:

Image

HA App Settings:

Image

Hermit Lite App (with fullscreen mode enabled inside hermit):

Image

**Additional information:**

### PR DESCRIPTION
**Pull request by TimoPtr**
## Summary

This is an attempt to fix the issue with the topbar describe in #5539.
Based on the documentation we might need to invoke `installCompatInsetsDispatch` so that old APIs works properly when edge to edge is enabled. This PR does that by using a small wrapper around the edgeToEdge extension function.

## Checklist

- [ ] New or updated tests have been added to cover the changes following the testing [guidelines](https://developers.home-assistant.io/docs/android/testing/introduction).
- [x] The code follows the project's [code style](https://developers.home-assistant.io/docs/android/codestyle) and [best_practices](https://developers.home-assistant.io/docs/android/best_practices).
- [x] The changes have been thoroughly tested, and edge cases have been considered.
- [x] Changes are backward compatible whenever feasible. Any breaking changes are documented in the changelog for users and/or in the code for developers depending on the relevance.

## Any other notes

Fixes #5539

### CODE REVIEW

File: onboarding/src/main/kotlin/io/homeassistant/companion/android/util/ActivityExtensions.kt [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+ *
+ * Use this function instead of calling [enableEdgeToEdge] directly to ensure consistent
+ * edge-to-edge behavior across different Android API levels.
+ */
+fun ComponentActivity.enableEdgeToEdgeCompat() {
+    enableEdgeToEdge()
+    findViewById<View>(android.R.id.content).apply {
+        ViewGroupCompat.installCompatInsetsDispatch(this)
+    }
+}
```
Comment (TimoPtr) [inline onboarding/src/main/kotlin/io/homeassistant/companion/android/util/ActivityExtensions.kt:24]: This is going to be removed when we start moving things from onboarding to app

**Review by jpelgrom — APPROVED** [review]
Even when testing in emulators I am not able to reproduce the original issue, but users have confirmed it solves the issue and I do not see any way this will negatively impact the app.
