### PR TITLE
Calculate fan speed step count

### LINKED ISSUE #2815: Wear: Cannot slow down fan with less than 10 posible states
**Home Assistant Android version:** 2022.6.0-full

**Android version (phone):** 10

**Phone model:** SM-G965F

**Android version (watch):** 11 (Wear OS 3.2)

**Watch model:** SM-R860

**Home Assistant version:** 2022.8.6

**Last working Home Assistant release (if known):**

**Description of problem:**

The detail page of the fan component increases and decreases the speed with a fixed value of 10% instead of a dynamic value based on the fan capabilities. If you have a speed fan with less than ten possible speeds, it isn't an option to slow down the fan; you can only increase the fan speed.

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

image

**Additional information:**

### PR DESCRIPTION
**Pull request by wjtje**
## Summary

This PR changes the number of steps shown on the detail page of a fan entity because the default number of nine steps wouldn't work for fan entities with some percentage step size. This new function will calculate an optimal number of steps based on the percentage step size of the fan with a maximum of nine steps.

## Screenshots

**Before**:
Screenshot_20220825_115230_android

**After**:
image

**Before:**
Screenshot_20220825_115444_android

**After:**
image

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

## Any other notes

This fixes #2815

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @wjtje, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;android#2818).

Once you do that we will be able to review and accept this pull request.

Thanks!

File: common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt [hunk 1]
```diff
@@ -80,7 +81,25 @@ fun <T> Entity<T>.getFanSpeed(): EntityPosition? {
...
+        fun calculateNumStep(percentageStep: Double): Int {
+            val numSteps = round(100 / percentageStep).toInt()
+            if (numSteps <= 10) return numSteps
+            if (numSteps % 10 == 0) return 10
+            return calculateNumStep(percentageStep * 2)
+        }
+
+        return calculateNumStep(((attributes as Map<*, *>)["percentage_step"] as? Double)?.toDouble() ?: 1.0) - 1
+    } catch (e: Exception) {
+        Log.e(EntityExt.TAG, "Unable to get getFanPercentageStep")
```
Comment (jpelgrom) [inline common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt:102]: This should match the function name

```suggestion
        Log.e(EntityExt.TAG, "Unable to get getFanSteps")
```

**Review by jpelgrom — COMMENTED** [review]
Thanks for the bug report and fix! Tested it with different values and looks good to me.

Just one minor suggestion, now that you pointed out the incorrect log message in another function ;)

File: common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt (hunk 1 above)
Comment (wjtje) [reply common/src/main/java/io/homeassistant/companion/android/common/data/integration/Entity.kt]: Oops, I changed the function name at some point and didn't think about it anymore.

**Review by jpelgrom — APPROVED** [review]
