### PR TITLE
Save the last response so we can properly unsubscribe from events when the response ID has changed

### LINKED ISSUE #2774: App continues receiving state change events while the screen is off after connectivity change
**Home Assistant Android version:**

beta-2556-a6341251-full

**Android version:**

12

**Phone model:**

Pixel 6 Pro

**Home Assistant version:**

2022.8.1

**Description of problem:**

While the screen is turned off, I'm seeing state change events logged. Force closing app temporarily resolves.

Toggling cellular/wifi (to force a network change) and turning screen off within a few seconds sometimes triggers the issue.

**Additional information:**

Alternative trigger to #2750

<details>
<summary>Logs</summary>

```
08-07 15:14:09.119 17801 22849 E WebSocketRepository: Websocket: onFailure
08-07 15:14:09.119 17801 22849 E WebSocketRepository: java.net.SocketException: Software caused connection abort
08-07 15:14:09.119 17801 22849 E WebSocketRepository: at java.net.SocketInputStream.socketRead0(Native Method)
08-07 15:14:09.119 17801 22849 E WebSocketRepository: at java.net.SocketInputStream.socketRead(SocketInputStream.java:118)
08-07 15:14:09.119 17801 22849 E WebSocketRepository: at java.net.SocketInputStream.read(SocketInputStream.java:173)
08-07 15:14:09.119 17801 22849 E WebSocketRepository: at java.net.SocketInputStream.read(SocketInputStream.java:143)
08-07 15:14:09.119 17801 22849 E WebSocketRepository: at com.android.org.conscrypt.ConscryptEngineSocket.readFromSocket(ConscryptEngineSocket.java:945)
08-07 15:14:09.119 17801 22849 E WebSocketRepository: at com.android.org.conscrypt.ConscryptEngineSocket.processDataFromSocket(ConscryptEngineSocket.java:909)
08-07 15:14:09.119 17801 22849 E WebSocketRepository: at com.android.org.conscrypt.ConscryptEngineSocket.readUntilDataAvailable(ConscryptEngineSocket.java:824)
08-07 15:14:09.119 17801 22849 E WebSocketRepository: at com.android.org.conscrypt.ConscryptEngineSocket.read(ConscryptEngineSocket.java:797)
08-07 15:14:09.119 17801 22849 E WebSocketRepository: at okio.InputStreamSource.read(JvmOkio.kt:94)
08-07 15:14:09.119 17801 22849 E WebSocketRepository: at okio.AsyncTimeout.read(AsyncTimeout.kt:125)
08-07 15:14:09.119 17801 22849 E WebSocketRepository: at okio.RealBufferedSource.request(RealBufferedSource.kt:206)
08-07 15:14:09.119 17801 22849 E WebSocketRepository: at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
08-07 15:14:09.119 17801 22849 E WebSocketRepository: at okio.RealBufferedSource.readByte(RealBufferedSource.kt:209)
08-07 15:14:09.119 17801 22849 E WebSocketRepository: at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:119)
08-07 15:14:09.119 17801 22849 E WebSocketRepository: at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:102)
08-07 15:14:09.119 17801 22849 E WebSocketRepository: at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
08-07 15:14:09.119 17801 22849 E WebSocketRepository: at okhttp3.internal.ws.RealWebSocket.onResponse(RealWebSocket.kt:195)
08-07 15:14:09.119 17801 22849 E WebSocketRepository: at okhttp3.internal.connection.RealCall.run(RealCall.kt:519)
08-07 15:14:09.119 17801 22849 E WebSocketRepository: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
08-07 15:14:09.119 17801 22849 E WebSocketRepository: at java.util.concurrent.ThreadPoolExecutor.run(ThreadPoolExecutor.java:637)
08-07 15:14:09.119 17801 22849 E WebSocketRepository: at java.lang.Thread.run(Thread.java:1012)
08-07 15:14:09.125 17801 17801 E TemplateWidget: Unable to render template: {{ state_attr('sensor.status_report', 'report') }}
08-07 15:14:09.126 17801 17801 E TemplateWidget: Unable to render template: {{ state_attr('sensor.status_report', 'report') }}
08-07 15:14:10.823 17801 17801 D SensorReceiver: Received intent: android.net.wifi.WIFI_STATE_CHANGED
08-07 15:14:10.823 17801 17801 D SensorReceiver: Sensor wifi_state corresponding to received event android.net.wifi.WIFI_STATE_CHANGED is disabled, skipping sensors update
08-07 15:14:11.168 17801 17801 D SensorReceiver: Received intent: android.net.wifi.WIFI_STATE_CHANGED
08-07 15:14:11.169 17801 17801 D SensorReceiver: Sensor wifi_state corresponding to received event android.net.wifi.WIFI_STATE_CHANGED is disabled, skipping sensors update
08-07 15:14:11.434 17801 26923 D UrlRepository: localUrl is: false and usesInternalSsid is: false
08-07 15:14:11.435 17801 17855 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=b38d7fe0-143a-4ff2-a774-6ae872271102, tags={ io.homeassistant.companion.android.websocket.WebsocketManager } ]
08-07 15:14:14.240 17801 17801 D SensorReceiver: Received intent: android.net.wifi.STATE_CHANGE
08-07 15:14:14.241 17801 17801 D LastUpdate: Last update is android.net.wifi.STATE_CHANGE
08-07 15:14:14.251 17801 26923 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:14.252 17801 26923 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:14.265 17801 26923 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:14.266 17801 17828 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=455508ce-55d1-4b33-830e-8271d8d7e7db, tags={ io.homeassistant.companion.android.websocket.WebsocketManager } ]
08-07 15:14:14.267 17801 18106 E SensorReceiver: Error while getting core config to sync sensor status
08-07 15:14:14.267 17801 18106 D ActivitySM: Unregistering for activity updates.
08-07 15:14:14.268 17801 18106 D ActivitySM: Registering for activity updates.
08-07 15:14:14.323 17801 18106 D NextAlarm: Next alarm is scheduled by com.google.android.deskclock with trigger time 1659958200000
08-07 15:14:14.343 17801 18106 D SensorReceiver: Nothing to update
08-07 15:14:14.734 17801 17801 D SensorReceiver: Received intent: android.net.wifi.STATE_CHANGE
08-07 15:14:14.735 17801 17801 D LastUpdate: Last update is android.net.wifi.STATE_CHANGE
08-07 15:14:14.738 17801 18106 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:14.740 17801 18106 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:14.744 17801 18106 E SensorReceiver: Error while getting core config to sync sensor status
08-07 15:14:14.745 17801 18106 D ActivitySM: Unregistering for activity updates.
08-07 15:14:14.745 17801 18106 D ActivitySM: Registering for activity updates.
08-07 15:14:14.761 17801 26923 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:14.761 17801 17828 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=780544a7-dfe7-45a5-a2a7-a80dc2f1b89c, tags={ io.homeassistant.companion.android.websocket.WebsocketManager } ]
08-07 15:14:14.809 17801 17801 D SensorReceiver: Received intent: android.net.wifi.STATE_CHANGE
08-07 15:14:14.814 17801 17801 D LastUpdate: Last update is android.net.wifi.STATE_CHANGE
08-07 15:14:14.820 17801 17801 D SensorReceiver: Received intent: android.net.wifi.STATE_CHANGE
08-07 15:14:14.821 17801 17801 D LastUpdate: Last update is android.net.wifi.STATE_CHANGE
08-07 15:14:14.836 17801 18106 D NextAlarm: Next alarm is scheduled by com.google.android.deskclock with trigger time 1659958200000
08-07 15:14:14.855 17801 18106 D SensorReceiver: Nothing to update
08-07 15:14:14.889 17801 22985 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:14.891 17801 23752 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:14.891 17801 18212 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:14.892 17801 17854 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=01abfeb9-3745-4f74-b750-76c17372f47e, tags={ io.homeassistant.companion.android.websocket.WebsocketManager } ]
08-07 15:14:15.063 17801 18212 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:15.065 17801 22985 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:15.068 17801 18212 E SensorReceiver: Error while getting core config to sync sensor status
08-07 15:14:15.069 17801 22985 E SensorReceiver: Error while getting core config to sync sensor status
08-07 15:14:15.069 17801 18212 D ActivitySM: Unregistering for activity updates.
08-07 15:14:15.069 17801 18212 D ActivitySM: Registering for activity updates.
08-07 15:14:15.070 17801 22985 D ActivitySM: Unregistering for activity updates.
08-07 15:14:15.070 17801 22985 D ActivitySM: Registering for activity updates.
08-07 15:14:15.218 17801 18212 D NextAlarm: Next alarm is scheduled by com.google.android.deskclock with trigger time 1659958200000
08-07 15:14:15.221 17801 22985 D NextAlarm: Next alarm is scheduled by com.google.android.deskclock with trigger time 1659958200000
08-07 15:14:15.256 17801 18212 D SensorReceiver: Nothing to update
08-07 15:14:15.257 17801 22985 D SensorReceiver: Nothing to update
08-07 15:14:18.092 17801 17801 D SensorReceiver: Received intent: android.net.wifi.STATE_CHANGE
08-07 15:14:18.093 17801 17801 D LastUpdate: Last update is android.net.wifi.STATE_CHANGE
08-07 15:14:18.125 17801 17801 D SensorReceiver: Received intent: android.net.wifi.STATE_CHANGE
08-07 15:14:18.126 17801 17801 D LastUpdate: Last update is android.net.wifi.STATE_CHANGE
08-07 15:14:18.133 17801 22985 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:18.134 17801 18106 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:18.134 17801 18212 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:18.135 17801 22985 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:18.135 17801 17855 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=f085652d-8ba6-450b-b05b-e496638f0cc8, tags={ io.homeassistant.companion.android.websocket.WebsocketManager } ]
08-07 15:14:18.138 17801 18212 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:18.142 17801 18212 E SensorReceiver: Error while getting core config to sync sensor status
08-07 15:14:18.143 17801 18212 D ActivitySM: Unregistering for activity updates.
08-07 15:14:18.143 17801 18212 D ActivitySM: Registering for activity updates.
08-07 15:14:18.145 17801 22985 E SensorReceiver: Error while getting core config to sync sensor status
08-07 15:14:18.146 17801 22985 D ActivitySM: Unregistering for activity updates.
08-07 15:14:18.146 17801 22985 D ActivitySM: Registering for activity updates.
08-07 15:14:18.168 17801 17801 D LocBroadcastReceiver: Received location update.
08-07 15:14:18.170 17801 17801 D ForegrndServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = false
08-07 15:14:18.170 17801 17801 D LocBroadcastReceiver: Last Location: 
08-07 15:14:18.170 17801 17801 D LocBroadcastReceiver: Coords:(x, y)
08-07 15:14:18.170 17801 17801 D LocBroadcastReceiver: Accuracy: 13.35
08-07 15:14:18.170 17801 17801 D LocBroadcastReceiver: Bearing: 0.0
08-07 15:14:18.170 17801 17801 D LocBroadcastReceiver: Begin evaluating if location update should be skipped
08-07 15:14:18.170 17801 17801 D LocBroadcastReceiver: Received location that is 35533 milliseconds old, 1659899622637 compared to 1659899658170 with source fused
08-07 15:14:18.178 17801 26923 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:18.188 17801 26923 E LocBroadcastReceiver: Could not update location.
08-07 15:14:18.272 17801 17801 D LocBroadcastReceiver: Received location update.
08-07 15:14:18.273 17801 17801 D ForegrndServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = false
08-07 15:14:18.273 17801 17801 D LocBroadcastReceiver: Last Location: 
08-07 15:14:18.273 17801 17801 D LocBroadcastReceiver: Coords:(x, y)
08-07 15:14:18.273 17801 17801 D LocBroadcastReceiver: Accuracy: 13.35
08-07 15:14:18.273 17801 17801 D LocBroadcastReceiver: Bearing: 0.0
08-07 15:14:18.273 17801 17801 D LocBroadcastReceiver: Begin evaluating if location update should be skipped
08-07 15:14:18.273 17801 17801 D LocBroadcastReceiver: Received location that is 62 milliseconds old, 1659899658211 compared to 1659899658273 with source fused
08-07 15:14:18.273 17801 17801 D LocBroadcastReceiver: Duplicate location received, not sending to HA
08-07 15:14:18.421 17801 22985 D NextAlarm: Next alarm is scheduled by com.google.android.deskclock with trigger time 1659958200000
08-07 15:14:18.428 17801 18212 D NextAlarm: Next alarm is scheduled by com.google.android.deskclock with trigger time 1659958200000
08-07 15:14:18.502 17801 22985 D SensorReceiver: Nothing to update
08-07 15:14:18.512 17801 18212 D SensorReceiver: Nothing to update
08-07 15:14:19.123 17801 18212 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:19.123 17801 18212 D UrlRepository: Using external URL
08-07 15:14:19.124 17801 18212 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:19.124 17801 18212 D UrlRepository: Using external URL
08-07 15:14:19.196 17801 22849 D WebSocketRepository: Websocket: onOpen
08-07 15:14:19.199 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:19.199 17801 22849 D WebSocketRepository: Message number null received: {"type":"auth_required","ha_version":"2022.8.1"}
08-07 15:14:19.199 17801 18212 D WebSocketRepository: Auth Requested
08-07 15:14:19.203 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:19.203 17801 22849 D WebSocketRepository: Message number null received: {"type":"auth_ok","ha_version":"2022.8.1"}
08-07 15:14:19.203 17801 18212 D WebSocketRepository: Sending message 58: {type=subscribe_events, event_type=state_changed, id=58}
08-07 15:14:19.204 17801 18212 D WebSocketRepository: Message number 58 sent
08-07 15:14:19.211 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:19.211 17801 22849 D WebSocketRepository: Message number 58 received: {"id":58,"type":"result","success":true,"result":null}
08-07 15:14:19.763 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:19.764 17801 22849 D WebSocketRepository: Message number 58 received: {"id":58,"type":"event","event":{"event_type":"state_changed",[...]
08-07 15:14:19.764 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:19.764 17801 22849 D WebSocketRepository: Message number 58 received: {"id":58,"type":"event","event":{"event_type":"state_changed",[...]
08-07 15:14:19.764 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:19.765 17801 22849 D WebSocketRepository: Message number 58 received: {"id":58,"type":"event","event":{"event_type":"state_changed",[...]
08-07 15:14:19.765 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:19.765 17801 22849 D WebSocketRepository: Message number 58 received: {"id":58,"type":"event","event":{"event_type":"state_changed",[...]
08-07 15:14:19.775 17801 17801 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:19.779 17801 17801 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:19.782 17801 17801 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:19.785 17801 17801 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:20.299 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:20.300 17801 22849 D WebSocketRepository: Message number 58 received: {"id":58,"type":"event","event":{"event_type":"state_changed",[...]
08-07 15:14:20.301 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:20.301 17801 22849 D WebSocketRepository: Message number 58 received: {"id":58,"type":"event","event":{"event_type":"state_changed",[...]
08-07 15:14:20.302 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:20.302 17801 22849 D WebSocketRepository: Message number 58 received: {"id":58,"type":"event","event":{"event_type":"state_changed",[...]
08-07 15:14:20.302 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:20.303 17801 22849 D WebSocketRepository: Message number 58 received: {"id":58,"type":"event","event":{"event_type":"state_changed",[...]
08-07 15:14:20.309 17801 17801 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:20.311 17801 17801 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:20.314 17801 17801 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:20.316 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:20.316 17801 22849 D WebSocketRepository: Message number 58 received: {"id":58,"type":"event","event":{"event_type":"state_changed",[...]
08-07 15:14:20.317 17801 17801 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:20.318 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:20.318 17801 22849 D WebSocketRepository: Message number 58 received: {"id":58,"type":"event","event":{"event_type":"state_changed",[...]
08-07 15:14:20.318 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:20.318 17801 22849 D WebSocketRepository: Message number 58 received: {"id":58,"type":"event","event":{"event_type":"state_changed",[...]
08-07 15:14:20.318 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:20.318 17801 22849 D WebSocketRepository: Message number 58 received: {"id":58,"type":"event","event":{"event_type":"state_changed",[...]
08-07 15:14:20.326 17801 17801 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:20.330 17801 17801 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:20.333 17801 17801 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:20.336 17801 17801 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:21.327 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:21.328 17801 22849 D WebSocketRepository: Message number 58 received: {"id":58,"type":"event","event":{"event_type":"state_changed",[...]
08-07 15:14:21.328 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:21.328 17801 22849 D WebSocketRepository: Message number 58 received: {"id":58,"type":"event","event":{"event_type":"state_changed",[...]
08-07 15:14:21.328 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:21.328 17801 22849 D WebSocketRepository: Message number 58 received: {"id":58,"type":"event","event":{"event_type":"state_changed",[...]
08-07 15:14:21.329 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:21.329 17801 22849 D WebSocketRepository: Message number 58 received: {"id":58,"type":"event","event":{"event_type":"state_changed",[...]
08-07 15:14:21.330 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:21.330 17801 22849 D WebSocketRepository: Message number 58 received: {"id":58,"type":"event","event":{"event_type":"state_changed",[...]
08-07 15:14:21.336 17801 17801 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:21.341 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:21.342 17801 22849 D WebSocketRepository: Message number 58 received: {"id":58,"type":"event","event":{"event_type":"state_changed",[...]
08-07 15:14:21.342 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:21.342 17801 22849 D WebSocketRepository: Message number 58 received: {"id":58,"type":"event","event":{"event_type":"state_changed",[...]
08-07 15:14:21.342 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:21.342 17801 22849 D WebSocketRepository: Message number 58 received: {"id":58,"type":"event","event":{"event_type":"state_changed",[...]
08-07 15:14:21.345 17801 17801 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:21.350 17801 17801 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:21.352 17801 17801 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:21.354 17801 17801 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:21.357 17801 17801 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:21.359 17801 17801 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:21.361 17801 17801 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:21.906 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:21.907 17801 22849 D WebSocketRepository: Message number 58 received: {"id":58,"type":"event","event":{"event_type":"state_changed",[...]
08-07 15:14:21.919 17801 17801 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:22.387 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:22.388 17801 22849 D WebSocketRepository: Message number 58 received: {"id":58,"type":"event","event":{"event_type":"state_changed",[...]
08-07 15:14:22.388 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:22.388 17801 22849 D WebSocketRepository: Message number 58 received: {"id":58,"type":"event","event":{"event_type":"state_changed",[...]
08-07 15:14:22.388 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:22.388 17801 22849 D WebSocketRepository: Message number 58 received: {"id":58,"type":"event","event":{"event_type":"state_changed",[...]
08-07 15:14:22.388 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:22.389 17801 22849 D WebSocketRepository: Message number 58 received: {"id":58,"type":"event","event":{"event_type":"state_changed",[...]
08-07 15:14:22.396 17801 17801 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:22.402 17801 17801 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:22.405 17801 17801 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:22.410 17801 17801 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:22.722 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:22.723 17801 22849 D WebSocketRepository: Message number 58 received: {"id":58,"type":"event","event":{"event_type":"state_changed",[...]
08-07 15:14:22.733 17801 17801 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:22.884 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:22.884 17801 22849 D WebSocketRepository: Message number 58 received: {"id":58,"type":"event","event":{"event_type":"state_changed",[...]
08-07 15:14:22.894 17801 17801 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:24.039 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:24.040 17801 22849 D WebSocketRepository: Message number 58 received: {"id":58,"type":"event","event":{"event_type":"state_changed",[...]
08-07 15:14:24.041 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:24.041 17801 22849 D WebSocketRepository: Message number 58 received: {"id":58,"type":"event","event":{"event_type":"state_changed",[...]
08-07 15:14:24.153 17801 17801 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:24.159 17801 17801 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:24.209 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:24.210 17801 22849 D WebSocketRepository: Message number 58 received: {"id":58,"type":"event","event":{"event_type":"state_changed",[...]
08-07 15:14:24.210 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:24.211 17801 22849 D WebSocketRepository: Message number 58 received: {"id":58,"type":"event","event":{"event_type":"state_changed",[...]
08-07 15:14:24.222 17801 17801 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:24.225 17801 17801 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:24.795 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:24.796 17801 22849 D WebSocketRepository: Message number 58 received: {"id":58,"type":"event","event":{"event_type":"state_changed",[...]
08-07 15:14:24.803 17801 17801 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:25.096 17801 17801 D ActivitySM: Received activity update.
08-07 15:14:25.098 17801 17801 D SensorReceiver: Received intent: android.intent.action.SCREEN_OFF
08-07 15:14:25.098 17801 17801 D SensorReceiver: Sensor is_interactive corresponding to received event android.intent.action.SCREEN_OFF is disabled, skipping sensors update
08-07 15:14:25.100 17801 17801 D ButtonWidget: Broadcast received: 
08-07 15:14:25.100 17801 17801 D ButtonWidget: Broadcast action: android.intent.action.SCREEN_OFF
08-07 15:14:25.100 17801 17801 D ButtonWidget: AppWidgetId: -1
08-07 15:14:25.102 17801 17801 D MediaPlayCtrlsWidget: Broadcast received: 
08-07 15:14:25.102 17801 17801 D MediaPlayCtrlsWidget: Broadcast action: android.intent.action.SCREEN_OFF
08-07 15:14:25.102 17801 17801 D MediaPlayCtrlsWidget: AppWidgetId: -1
08-07 15:14:25.104 17801 17831 D WebSocketRepository: Unsubscribing from state_changed
08-07 15:14:25.104 17801 17831 D WebSocketRepository: Sending message 59: {type=unsubscribe_events, subscription=57, id=59}
08-07 15:14:25.104 17801 17831 D WebSocketRepository: Message number 59 sent
08-07 15:14:25.121 17801 17831 D UrlRepository: localUrl is: false and usesInternalSsid is: true
08-07 15:14:25.122 17801 17855 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=22ebb032-da5b-4e6a-a6bd-76cb0f4b33d6, tags={ io.homeassistant.companion.android.websocket.WebsocketManager } ]
08-07 15:14:25.215 17801 22849 D WebSocketRepository: Websocket: onMessage (text)
08-07 15:14:25.216 17801 22849 D WebSocketRepository: Message number 58 received: {"id":58,"type":"event","event":{"event_type":"state_changed",[...]
```
</details>

### PR DESCRIPTION
**Pull request by dshokouhi**
## Summary

This PR attempts to fix #2774 by keeping track of the `lastResponse` so we can unsubscribe with the correct response ID.

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

### CODE REVIEW

File: common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt [hunk 1]
```diff
@@ -201,7 +202,7 @@ class WebSocketRepositoryImpl @Inject constructor(
                             sendMessage(
                                 mapOf(
                                     "type" to "unsubscribe_events",
-                                    "subscription" to response.id
+                                    "subscription" to lastResponse!!.id
```
Comment (jpelgrom) [inline common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt:205]: `lastResponse` might be `null` at this point if a later subscription request returned `null`.

**Review by jpelgrom — COMMENTED** [review]
This will create problems when using multiple subscriptions of different types, for example when adding device controls or in the Wear OS app. The app will try to unsubscribe from _all_ subscriptions with the ID of the _last_ subscription.

<details>
<summary>Example from the Wear app, logcat output</summary>

Note the subscriptions are:
`5` events
`6` area registry
`7` device registry
`8` entity registry

When unsubscribing it is sending `subscription=8` for all. The first one succeeds and all others fail because it is already cancelled. After all the unsubscribes a new event (subscription `5`) shows up.

```
2022-08-09 20:07:01.327 25389-25432/io.homeassistant.companion.android.debug D/WebSocketRepository: Websocket: onOpen
2022-08-09 20:07:01.335 25389-25432/io.homeassistant.companion.android.debug D/WebSocketRepository: Websocket: onMessage (text)
2022-08-09 20:07:02.690 25389-25432/io.homeassistant.companion.android.debug D/WebSocketRepository: Message number null received: {"type":"auth_required","ha_version":"2022.8.2"}
2022-08-09 20:07:02.693 25389-25432/io.homeassistant.companion.android.debug D/WebSocketRepository: Websocket: onMessage (text)
2022-08-09 20:07:02.695 25389-25440/io.homeassistant.companion.android.debug D/WebSocketRepository: Auth Requested
2022-08-09 20:07:02.703 25389-25432/io.homeassistant.companion.android.debug D/WebSocketRepository: Message number null received: {"type":"auth_ok","ha_version":"2022.8.2"}
2022-08-09 20:07:07.627 25389-25389/io.homeassistant.companion.android.debug D/WebSocketRepository: Sending message 1: {type=config/device_registry/list, id=1}
2022-08-09 20:07:07.637 25389-25389/io.homeassistant.companion.android.debug D/WebSocketRepository: Message number 1 sent
2022-08-09 20:07:07.637 25389-25389/io.homeassistant.companion.android.debug D/WebSocketRepository: Sending message 2: {type=config/entity_registry/list, id=2}
2022-08-09 20:07:07.638 25389-25389/io.homeassistant.companion.android.debug D/WebSocketRepository: Message number 2 sent
2022-08-09 20:07:07.640 25389-25389/io.homeassistant.companion.android.debug D/WebSocketRepository: Sending message 3: {type=get_states, id=3}
2022-08-09 20:07:07.641 25389-25389/io.homeassistant.companion.android.debug D/WebSocketRepository: Message number 3 sent
2022-08-09 20:07:07.642 25389-25389/io.homeassistant.companion.android.debug D/WebSocketRepository: Sending message 4: {type=config/area_registry/list, id=4}
2022-08-09 20:07:07.642 25389-25389/io.homeassistant.companion.android.debug D/WebSocketRepository: Message number 4 sent
2022-08-09 20:07:07.688 25389-25432/io.homeassistant.companion.android.debug D/WebSocketRepository: Websocket: onMessage (text)
2022-08-09 20:07:07.755 25389-25432/io.homeassistant.companion.android.debug D/WebSocketRepository: Message number 1 received: {"id":1,"type":"result","success":true,"result": ...
2022-08-09 20:07:07.773 25389-25432/io.homeassistant.companion.android.debug D/WebSocketRepository: Websocket: onMessage (text)
2022-08-09 20:07:07.919 25389-25432/io.homeassistant.companion.android.debug D/WebSocketRepository: Message number 2 received: {"id":2,"type":"result","success":true,"result": ...
2022-08-09 20:07:07.938 25389-25432/io.homeassistant.companion.android.debug D/WebSocketRepository: Websocket: onMessage (text)
2022-08-09 20:07:08.032 25389-25432/io.homeassistant.companion.android.debug D/WebSocketRepository: Message number 3 received: {"id":3,"type":"result","success":true,"result": ...
2022-08-09 20:07:08.034 25389-25432/io.homeassistant.companion.android.debug D/WebSocketRepository: Websocket: onMessage (text)
2022-08-09 20:07:08.036 25389-25432/io.homeassistant.companion.android.debug D/WebSocketRepository: Message number 4 received: {"id":4,"type":"result","success":true,"result": ...
2022-08-09 20:07:09.216 25389-25389/io.homeassistant.companion.android.debug D/WebSocketRepository: Sending message 5: {type=subscribe_events, event_type=state_changed, id=5}
2022-08-09 20:07:09.218 25389-25389/io.homeassistant.companion.android.debug D/WebSocketRepository: Message number 5 sent
2022-08-09 20:07:09.233 25389-25432/io.homeassistant.companion.android.debug D/WebSocketRepository: Websocket: onMessage (text)
2022-08-09 20:07:09.239 25389-25432/io.homeassistant.companion.android.debug D/WebSocketRepository: Message number 5 received: {"id":5,"type":"result","success":true,"result":null}
2022-08-09 20:07:09.977 25389-25389/io.homeassistant.companion.android.debug D/WebSocketRepository: Sending message 6: {type=subscribe_events, event_type=area_registry_updated, id=6}
2022-08-09 20:07:09.979 25389-25389/io.homeassistant.companion.android.debug D/WebSocketRepository: Message number 6 sent
2022-08-09 20:07:10.005 25389-25432/io.homeassistant.companion.android.debug D/WebSocketRepository: Websocket: onMessage (text)
2022-08-09 20:07:10.018 25389-25432/io.homeassistant.companion.android.debug D/WebSocketRepository: Message number 6 received: {"id":6,"type":"result","success":true,"result":null}
2022-08-09 20:07:10.245 25389-25389/io.homeassistant.companion.android.debug D/WebSocketRepository: Sending message 7: {type=subscribe_events, event_type=device_registry_updated, id=7}
2022-08-09 20:07:10.247 25389-25389/io.homeassistant.companion.android.debug D/WebSocketRepository: Message number 7 sent
2022-08-09 20:07:10.267 25389-25432/io.homeassistant.companion.android.debug D/WebSocketRepository: Websocket: onMessage (text)
2022-08-09 20:07:10.271 25389-25432/io.homeassistant.companion.android.debug D/WebSocketRepository: Message number 7 received: {"id":7,"type":"result","success":true,"result":null}
2022-08-09 20:07:10.310 25389-25389/io.homeassistant.companion.android.debug D/WebSocketRepository: Sending message 8: {type=subscribe_events, event_type=entity_registry_updated, id=8}
2022-08-09 20:07:10.314 25389-25389/io.homeassistant.companion.android.debug D/WebSocketRepository: Message number 8 sent
2022-08-09 20:07:10.331 25389-25432/io.homeassistant.companion.android.debug D/WebSocketRepository: Websocket: onMessage (text)
2022-08-09 20:07:10.346 25389-25432/io.homeassistant.companion.android.debug D/WebSocketRepository: Message number 8 received: {"id":8,"type":"result","success":true,"result":null}
2022-08-09 20:07:17.926 25389-25432/io.homeassistant.companion.android.debug D/WebSocketRepository: Websocket: onMessage (text)
2022-08-09 20:07:17.935 25389-25432/io.homeassistant.companion.android.debug D/WebSocketRepository: Message number 5 received: {"id":5,"type":"event","event":{"event_type":"state_changed","data" ...
2022-08-09 20:07:20.395 25389-25451/io.homeassistant.companion.android.debug D/WebSocketRepository: Unsubscribing from state_changed
2022-08-09 20:07:20.413 25389-25442/io.homeassistant.companion.android.debug D/WebSocketRepository: Unsubscribing from area_registry_updated
2022-08-09 20:07:20.419 25389-25440/io.homeassistant.companion.android.debug D/WebSocketRepository: Unsubscribing from device_registry_updated
2022-08-09 20:07:20.432 25389-25441/io.homeassistant.companion.android.debug D/WebSocketRepository: Sending message 9: {type=unsubscribe_events, subscription=8, id=9}
2022-08-09 20:07:20.448 25389-25441/io.homeassistant.companion.android.debug D/WebSocketRepository: Message number 9 sent
2022-08-09 20:07:20.449 25389-25455/io.homeassistant.companion.android.debug D/WebSocketRepository: Sending message 10: {type=unsubscribe_events, subscription=8, id=10}
2022-08-09 20:07:20.453 25389-25455/io.homeassistant.companion.android.debug D/WebSocketRepository: Message number 10 sent
2022-08-09 20:07:20.458 25389-25453/io.homeassistant.companion.android.debug D/WebSocketRepository: Sending message 11: {type=unsubscribe_events, subscription=8, id=11}
2022-08-09 20:07:20.458 25389-25453/io.homeassistant.companion.android.debug D/WebSocketRepository: Message number 11 sent
2022-08-09 20:07:20.473 25389-25457/io.homeassistant.companion.android.debug D/WebSocketRepository: Unsubscribing from entity_registry_updated
2022-08-09 20:07:20.474 25389-25456/io.homeassistant.companion.android.debug D/WebSocketRepository: Sending message 12: {type=unsubscribe_events, subscription=8, id=12}
2022-08-09 20:07:20.475 25389-25456/io.homeassistant.companion.android.debug D/WebSocketRepository: Message number 12 sent
2022-08-09 20:07:20.482 25389-25432/io.homeassistant.companion.android.debug D/WebSocketRepository: Websocket: onMessage (text)
2022-08-09 20:07:20.497 25389-25432/io.homeassistant.companion.android.debug D/WebSocketRepository: Message number 9 received: {"id":9,"type":"result","success":true,"result":null}
2022-08-09 20:07:20.498 25389-25432/io.homeassistant.companion.android.debug D/WebSocketRepository: Websocket: onMessage (text)
2022-08-09 20:07:20.500 25389-25432/io.homeassistant.companion.android.debug D/WebSocketRepository: Message number 10 received: {"id":10,"type":"result","success":false,"error":{"code":"not_found","message":"Subscription not found."}}
2022-08-09 20:07:20.508 25389-25432/io.homeassistant.companion.android.debug D/WebSocketRepository: Websocket: onMessage (text)
2022-08-09 20:07:20.511 25389-25432/io.homeassistant.companion.android.debug D/WebSocketRepository: Message number 11 received: {"id":11,"type":"result","success":false,"error":{"code":"not_found","message":"Subscription not found."}}
2022-08-09 20:07:20.516 25389-25432/io.homeassistant.companion.android.debug D/WebSocketRepository: Websocket: onMessage (text)
2022-08-09 20:07:20.524 25389-25432/io.homeassistant.companion.android.debug D/WebSocketRepository: Message number 12 received: {"id":12,"type":"result","success":false,"error":{"code":"not_found","message":"Subscription not found."}}
2022-08-09 20:07:27.996 25389-25432/io.homeassistant.companion.android.debug D/WebSocketRepository: Websocket: onMessage (text)
2022-08-09 20:07:28.034 25389-25432/io.homeassistant.companion.android.debug D/WebSocketRepository: Message number 5 received: {"id":5,"type":"event","event":{"event_type":"state_changed","data": ...
```

File: common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt (hunk 1 above)
Comment (dshokouhi) [reply common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt:205]: but if a later subscription returned `null` wouldn't we already exit the method before reaching here?

**Comment by dshokouhi** [comment]
> This will create problems when using multiple subscriptions of different types, for example when adding device controls or in the Wear OS app. The app will try to unsubscribe from _all_ subscriptions with the ID of the _last_ subscription.

Thanks I didn't see this initially but it seems my logcat filtering was not correct 🤦

File: common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt (hunk 1 above)
Comment (jpelgrom) [reply common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt:205]: I don't think so? This is a callback, and returning if we receive `null` is outside the callback.

Imagine the first subscription works, receives ID `x` in `lastResponse`. The flow is setup and the callback is set. Now the app wants another subscription which fails, so `lastResponse` is set to `null` and no flow is created. When the app later stops listening to the first subscription, it will try to execute the callback but `lastResponse` is now `null` instead of something with ID `x`.

Comment (dshokouhi) [reply common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt:205]: hmm so in this particular case then my idea of keeping track of the last response is not good then 🤔

Comment (jpelgrom) [reply common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt:205]: I wouldn't consider this the 'last response', but rather the 'last subscription id'. It should be scoped to `eventType` like everything else in this function.

Comment (dshokouhi) [reply common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt:205]: so an additional variable(s) to keep track of the last ID per subscription when its not null? ok this is going to get out of hand if we add anything else lol. Am I understanding that correctly?

Comment (jpelgrom) [reply common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt:205]: I think

```
private var lastResponse = mutableMapOf<String, SocketResponse?>()
```

+ change `lastResponse` to `lastResponse[eventType]` when using it will work and isn't a lot of changes.

**Comment by dshokouhi** [comment]
Ok looks like the subscriptions and unsubscriptions are working as expected now

File: common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt (hunk 1 above)
Comment (dshokouhi) [reply common/src/main/java/io/homeassistant/companion/android/common/data/websocket/impl/WebSocketRepositoryImpl.kt]: Just saw your edit. Adding it now :)

**Comment by jpelgrom** [comment]
It works and fixes the bug the user mentioned in their comment on the issue 👍

Potential improvement: store only the `id` in the response that is returned instead of the entire response, as only the ID is used.

**Comment by dshokouhi** [comment]
> Potential improvement: store only the `id` in the response that is returned instead of the entire response, as only the ID is used.

Done, now only storing the ID :)

**Review by jpelgrom — APPROVED** [review]

**Review by JBassett — APPROVED** [review]
