### PR TITLE
Refactor Assist audio recording to fix race condition using Channel

### LINKED ISSUE #6048: Assist on WearOS closes without actioning request
**Home Assistant Android app version(s):**
2025.11.1
**Android version(s):**
Android 15
 WearOS 5

**Device model(s):**
Samsung S23 PLus:
Samsung Galaxy watch6  

**Home Assistant version:**
2025.10.4
**Last working Home Assistant release (if known):**
Last Stable Update
**Description of problem, include YAML if issue is related to notifications:**

When I try and run assist from my WearOS app, it opens, then after 5 seconds closes, before performing any actions

Here is a link to a video of me trying

https://photos.app.goo.gl/YbqtTe9epSzFpP7G8

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

### PR DESCRIPTION
**Pull request by TimoPtr**
## Summary

Refactored the audio recording pipeline in AssistViewModelBase to fix a race condition when buffering audio data before STT is ready.

The issue was mostly seen when using a watch, but also on other low end devices. The issue was that the `queue` was nullify before all the data were fully sent. The new approach is to use a channel to store the data and make sure that we only use this to send the data. We only send the data when we reach the SST_START event.

## Checklist

- [x] New or updated tests have been added to cover the changes following the testing [guidelines](https://developers.home-assistant.io/docs/android/testing/introduction).
- [x] The code follows the project's [code style](https://developers.home-assistant.io/docs/android/codestyle) and [best_practices](https://developers.home-assistant.io/docs/android/best_practices).
- [x] The changes have been thoroughly tested, and edge cases have been considered.
- [x] Changes are backward compatible whenever feasible. Any breaking changes are documented in the changelog for users and/or in the code for developers depending on the relevance.

## Any other notes

Based on #6188.
Fixes #6048

### CODE REVIEW

File: common/src/main/kotlin/io/homeassistant/companion/android/common/assist/AssistViewModelBase.kt [hunk 1]
```diff
@@ -246,20 +264,45 @@ abstract class AssistViewModelBase(
         return true
     }
 
-    protected fun setupRecorderQueue() {
-        recorderQueue = mutableListOf()
+    /**
+     * Sets up audio recording and buffering for voice input.
+     *
+     * Must be called before [runAssistPipelineInternal] for voice pipelines.
+     * Audio data is buffered until [handleSttStart] signals that the server is ready
```
Comment (jpelgrom) [inline common/src/main/kotlin/io/homeassistant/companion/android/common/assist/AssistViewModelBase.kt]: You're referring to a private function in 'public' documentation

```suggestion
     * Audio data is buffered until the server is ready
```

File: common/src/main/kotlin/io/homeassistant/companion/android/common/assist/AssistViewModelBase.kt [hunk 2]
```diff
@@ -279,23 +322,49 @@ abstract class AssistViewModelBase(
...
+        recorderJob?.cancel()
+        recorderJob = null
+        sttReady = null
+    }
+
+    private fun clearRecorderState() {
+        recorderJob = null
+        sttReady = null
+        binaryHandlerId = null
+    }
```
Comment (jpelgrom) [inline common/src/main/kotlin/io/homeassistant/companion/android/common/assist/AssistViewModelBase.kt]: Why do these both exist when they are so similar? You could call cancel before `clearRecorderState`.

Comment (TimoPtr) [reply common/src/main/kotlin/io/homeassistant/companion/android/common/assist/AssistViewModelBase.kt]: Indeed

**Review by jpelgrom — APPROVED** [review]
