### PR TITLE
Fix duplicate notifications by removing leftover WorkManager with different unique work name

### LINKED ISSUE #6066: Duplicate Notifications when using persistent connection (websocket)
**Home Assistant Android app version(s):** 2025.11.3-full

**Android version(s):** 16

**Device model(s):** Pixel 7

**Home Assistant version:** core-2025.11.2

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

Notifications sent to phone via the companion app are duplicated.
```yaml
action: notify.mobile_app_phone
data:
  message: Hello
```

**Companion App Logs:**

```
11-18 12:56:20.760  2345 27819 D LocationSensorManager: High accuracy mode disabled, because not in zone [1_zone.home_expanded]
11-18 12:56:21.027  2345 25178 D ServerConnectionInfo: usesVpn is: false
11-18 12:56:21.027  2345 27819 D ServerConnectionInfo: usesVpn is: false
11-18 12:56:21.031  2345 25178 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:56:21.031  2345 27819 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:56:21.032  2345 27819 D ServerConnectionInfo: usesVpn is: false
11-18 12:56:21.032  2345 25178 D ServerConnectionInfo: usesVpn is: false
11-18 12:56:21.034  2345 27819 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:56:21.035  2345 25178 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:56:21.230  2345 25178 D ServerConnectionInfo: usesVpn is: false
11-18 12:56:21.230  2345 14365 D ServerConnectionInfo: usesVpn is: false
11-18 12:56:21.232  2345 25178 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:56:21.232  2345 14365 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:56:21.256  2345   423 I SensorReceiverBase: Sensor updates and sync completed
11-18 12:56:21.265  2345 14365 I SensorReceiverBase: Sensor updates and sync completed
11-18 12:56:24.240  2345  2345 E mpanion.android: Invalid resource ID 0x00000000.
11-18 12:56:24.240  2345  2345 E mpanion.android: Invalid resource ID 0x00000000.
11-18 12:56:24.240  2345  2345 E mpanion.android: Invalid resource ID 0x00000000.
11-18 12:56:24.241  2345  2345 E mpanion.android: Invalid resource ID 0x00000000.
11-18 12:56:24.241  2345  2345 E mpanion.android: Invalid resource ID 0x00000000.
11-18 12:56:24.241  2345  2345 E mpanion.android: Invalid resource ID 0x00000000.
11-18 12:56:24.241  2345  2345 E mpanion.android: Invalid resource ID 0x00000000.
11-18 12:56:24.241  2345  2345 E mpanion.android: Invalid resource ID 0x00000000.
11-18 12:56:24.241  2345  2345 E mpanion.android: Invalid resource ID 0x00000000.
11-18 12:56:24.241  2345  2345 E mpanion.android: Invalid resource ID 0x00000000.
11-18 12:56:24.247  2345  2345 D IntegrationRepositoryImpl: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 1763492076957, currentMillis: 1763492184247)
11-18 12:56:24.265  2345  2345 D ImeBackDispatcher: switch root view (mImeCallbacks.size=0)
11-18 12:56:24.268  2345  2345 D InsetsController: hide(ime())
11-18 12:56:24.268  2345  2345 I ImeTracker: io.homeassistant.companion.android:51cc3e6e: onCancelled at PHASE_CLIENT_ALREADY_HIDDEN
11-18 12:56:24.269  2345  2345 D IntegrationRepositoryImpl: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 1763492076957, currentMillis: 1763492184268)
11-18 12:56:24.270  2345  2345 D IntegrationRepositoryImpl: setAppActive(): true
11-18 12:56:28.846  2345  2345 E mpanion.android: Invalid resource ID 0x00000000.
11-18 12:56:29.356  2345  2345 E mpanion.android: Invalid resource ID 0x00000000.
11-18 12:56:29.757  2345  2345 E mpanion.android: Invalid resource ID 0x00000000.
11-18 12:56:29.780  2345  2345 D WindowOnBackDispatcher: setTopOnBackInvokedCallback (unwrapped): androidx.activity.OnBackPressedDispatcher$Api34Impl$createOnBackAnimationCallback$1@5c167be
11-18 12:56:29.859  2345  2345 E mpanion.android: Invalid resource ID 0x00000000.
11-18 12:56:29.859  2345  2345 E mpanion.android: Invalid resource ID 0x00000000.
11-18 12:56:29.859  2345  2345 E mpanion.android: Invalid resource ID 0x00000000.
11-18 12:56:29.859  2345  2345 E mpanion.android: Invalid resource ID 0x00000000.
11-18 12:56:29.859  2345  2345 E mpanion.android: Invalid resource ID 0x00000000.
11-18 12:56:33.251  2345  2345 E mpanion.android: Invalid resource ID 0x00000000.
11-18 12:56:33.306  2345 14365 D LogcatReader$readLog: Read logcat for pid 2345
11-18 12:56:33.381  2345 14365 D LogcatReader$readLog: Done reading logcat for pid 2345
11-18 12:56:33.698  2345   423 D ServerConnectionInfo: usesVpn is: false
11-18 12:56:33.698  2345 25178 D ServerConnectionInfo: usesVpn is: false
11-18 12:56:33.702  2345 25178 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:56:33.702  2345   423 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:56:33.703  2345 25178 D ServerConnectionInfo: usesVpn is: false
11-18 12:56:33.703  2345   423 D ServerConnectionInfo: usesVpn is: false
11-18 12:56:33.705  2345 25178 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:56:33.706  2345   423 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:56:33.706  2345 25178 D ServerConnectionInfo: usesVpn is: false
11-18 12:56:33.707  2345   423 D ServerConnectionInfo: usesVpn is: false
11-18 12:56:33.709  2345 25178 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:56:33.709  2345 25178 D ServerConnectionInfo: Using internal URL
11-18 12:56:33.711  2345   423 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:56:33.711  2345   423 D ServerConnectionInfo: Using internal URL
11-18 12:56:33.711  2345 25178 D ServerConnectionInfo: usesVpn is: false
11-18 12:56:33.713  2345 25178 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:56:33.714  2345 25178 D ServerConnectionInfo: usesVpn is: false
11-18 12:56:33.714  2345   423 D ServerConnectionInfo: usesVpn is: false
11-18 12:56:33.716  2345 25178 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:56:33.717  2345   423 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:56:33.717  2345 25178 D ServerConnectionInfo: usesVpn is: false
11-18 12:56:33.718  2345   423 D ServerConnectionInfo: usesVpn is: false
11-18 12:56:33.719  2345 25178 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:56:33.719  2345 25178 D ServerConnectionInfo: Using internal URL
11-18 12:56:33.720  2345 25178 D WebSocketCoreImpl$sendMessage: Sending message 3308: {type=ping, id=3308}
11-18 12:56:33.720  2345 25178 D WebSocketCoreImpl$sendMessage: Message number 3308 sent awaiting answer from WebSocket
11-18 12:56:33.720  2345   423 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:56:33.721  2345   423 D ServerConnectionInfo: usesVpn is: false
11-18 12:56:33.723  2345   423 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:56:33.723  2345   423 D ServerConnectionInfo: Using internal URL
11-18 12:56:33.724  2345   423 D WebSocketCoreImpl$sendMessage: Sending message 3309: {type=ping, id=3309}
11-18 12:56:33.725  2345   423 D WebSocketCoreImpl$sendMessage: Message number 3309 sent awaiting answer from WebSocket
11-18 12:56:33.737  2345  2541 D WebSocketCoreImpl: Websocket: onMessage (text)
11-18 12:56:33.740  2345  2541 D WebSocketCoreImpl: Message id 3308 received
11-18 12:56:33.740  2345  2541 D WebSocketCoreImpl: Websocket: onMessage (text)
11-18 12:56:33.741  2345  2541 D WebSocketCoreImpl: Message id 3309 received
11-18 12:56:42.341  2345  2345 D LocationSensorManager: Received location update.
11-18 12:56:42.347  2345  2345 D ForegroundServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = false
11-18 12:56:42.347  2345 25178 D LocationSensorManager: Last Location: 
11-18 12:56:42.347  2345 25178 D LocationSensorManager: Coords:(38.6732257, -90.3288059)
11-18 12:56:42.347  2345 25178 D LocationSensorManager: Accuracy: 100.0
11-18 12:56:42.347  2345 25178 D LocationSensorManager: Bearing: 0.0
11-18 12:56:42.348  2345 25178 D LocationSensorManager: Begin evaluating if location update should be skipped
11-18 12:56:42.348  2345 25178 D LocationSensorManager: Received location that is 54 milliseconds old, 1763492202294 compared to 1763492202348 with source fused
11-18 12:56:42.348  2345 25178 D LocationSensorManager: Duplicate location received, not sending to HA
11-18 12:56:51.053  2345  2541 D WebSocketCoreImpl: Websocket: onMessage (text)
11-18 12:56:51.066  2345  2541 D WebSocketCoreImpl: Message id 2075 received
11-18 12:56:51.084  2345 14365 D WebSocketCoreImpl$sendMessage: Sending message 3310: {type=mobile_app/push_notification_confirm, webhook_id=899e0cde7f88e2d8a6c9b7c41bf66fca5873296b49081e70f3143396d09e4ff6, confirm_id=58b5e2e53fa5396afbc91f25898d51bb, id=3310}
11-18 12:56:51.085  2345 14365 D WebSocketCoreImpl$sendMessage: Message number 3310 sent awaiting answer from WebSocket
11-18 12:56:51.086  2345 25178 D WebSocketCoreImpl$sendMessage: Sending message 3311: {type=mobile_app/push_notification_confirm, webhook_id=899e0cde7f88e2d8a6c9b7c41bf66fca5873296b49081e70f3143396d09e4ff6, confirm_id=58b5e2e53fa5396afbc91f25898d51bb, id=3311}
11-18 12:56:51.087  2345 25178 D WebSocketCoreImpl$sendMessage: Message number 3311 sent awaiting answer from WebSocket
11-18 12:56:51.090  2345  2541 D WebSocketCoreImpl: Websocket: onMessage (text)
11-18 12:56:51.092  2345  2541 D WebSocketCoreImpl: Message id 3310 received
11-18 12:56:51.093  2345  2541 D WebSocketCoreImpl: Websocket: onMessage (text)
11-18 12:56:51.094  2345  2541 D WebSocketCoreImpl: Message id 3311 received
11-18 12:56:51.104  2345  2345 D MessagingManager$handleMessage: Creating notification with following data: {message=Hello, webhook_id=899e0cde7f88e2d8a6c9b7c41bf66fca5873296b49081e70f3143396d09e4ff6, server_id=1}
11-18 12:56:51.118  2345  2345 D MessagingManager: Show notification with tag "null" and id "-1739347562"
11-18 12:56:51.120  2345  2345 D MessagingManager$handleMessage: Creating notification with following data: {message=Hello, webhook_id=899e0cde7f88e2d8a6c9b7c41bf66fca5873296b49081e70f3143396d09e4ff6, server_id=1}
11-18 12:56:51.125  2345  2345 D MessagingManager: Show notification with tag "null" and id "-1739347559"
11-18 12:56:54.258  2345  2345 D NotificationManagerExtensionsKt: Cancel notification with tag "null" and id "0"
11-18 12:56:54.259  2345  2345 D NotificationManagerExtensionsKt: Check if the notification is in a group...
11-18 12:56:54.259  2345  2345 D NotificationManagerExtensionsKt: Notification is not in a group. Cancel notification...
11-18 12:56:54.277  2345 30471 D ServerConnectionInfo: usesVpn is: false
11-18 12:56:54.282  2345 30471 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:56:56.002  2345 30471 D LogcatReader$readLog: Read logcat for pid 2345
11-18 12:56:56.022  2345 14365 D NotificationDeleteReceiver$onReceive: Notification cleared event successful!
11-18 12:56:56.064  2345 30471 D LogcatReader$readLog: Done reading logcat for pid 2345
11-18 12:56:56.101  2345  2386 I mpanion.android: Waiting for a blocking GC ProfileSaver
11-18 12:56:56.133  2345  2386 I mpanion.android: WaitForGcToComplete blocked ProfileSaver on Background for 31.370ms
11-18 12:57:00.023  2345  2345 D SensorReceiverBase: Received intent: android.intent.action.TIME_TICK
11-18 12:57:00.025  2345 30471 D LastUpdateManager: Last update is android.intent.action.TIME_TICK
11-18 12:57:00.029  2345 26413 D ServerConnectionInfo: usesVpn is: false
11-18 12:57:00.032  2345 26413 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:57:00.033  2345 26413 D ServerConnectionInfo: usesVpn is: false
11-18 12:57:00.034  2345 26413 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:57:00.034  2345 26413 D ServerConnectionInfo: Using internal URL
11-18 12:57:00.039  2345 26413 D ActivitySensorManager: Unregistering for activity updates.
11-18 12:57:00.041  2345 26413 D ActivitySensorManager: Registering for activity updates.
11-18 12:57:00.106  2345 14365 D ServerConnectionInfo: usesVpn is: false
11-18 12:57:00.108  2345 14365 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:57:00.151  2345 30471 D ForegroundServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = false
11-18 12:57:00.626  2345 30471 D ActivitySensorManager: Received activity update.
11-18 12:57:03.733  2345 30471 D ServerConnectionInfo: usesVpn is: false
11-18 12:57:03.733  2345 26413 D ServerConnectionInfo: usesVpn is: false
11-18 12:57:03.737  2345 30471 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:57:03.738  2345 26413 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:57:03.743  2345 26413 D ServerConnectionInfo: usesVpn is: false
11-18 12:57:03.743  2345 30471 D ServerConnectionInfo: usesVpn is: false
11-18 12:57:03.744  2345 26413 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:57:03.745  2345 26413 D ServerConnectionInfo: usesVpn is: false
11-18 12:57:03.746  2345 30471 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:57:03.747  2345 30471 D ServerConnectionInfo: usesVpn is: false
11-18 12:57:03.747  2345 26413 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:57:03.747  2345 26413 D ServerConnectionInfo: Using internal URL
11-18 12:57:03.748  2345 30471 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:57:03.748  2345 30471 D ServerConnectionInfo: Using internal URL
11-18 12:57:03.748  2345 26413 D ServerConnectionInfo: usesVpn is: false
11-18 12:57:03.749  2345 30471 D ServerConnectionInfo: usesVpn is: false
11-18 12:57:03.751  2345 30471 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:57:03.751  2345 26413 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:57:03.751  2345 30471 D ServerConnectionInfo: usesVpn is: false
11-18 12:57:03.751  2345 26413 D ServerConnectionInfo: usesVpn is: false
11-18 12:57:03.753  2345 26413 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:57:03.753  2345 30471 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:57:03.753  2345 26413 D ServerConnectionInfo: usesVpn is: false
11-18 12:57:03.753  2345 30471 D ServerConnectionInfo: usesVpn is: false
11-18 12:57:03.754  2345 26413 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:57:03.754  2345 26413 D ServerConnectionInfo: Using internal URL
11-18 12:57:03.756  2345 30471 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:57:03.756  2345 30471 D ServerConnectionInfo: Using internal URL
11-18 12:57:03.756  2345 26413 D WebSocketCoreImpl$sendMessage: Sending message 3312: {type=ping, id=3312}
11-18 12:57:03.762  2345 26413 D WebSocketCoreImpl$sendMessage: Message number 3312 sent awaiting answer from WebSocket
11-18 12:57:03.763  2345 30471 D WebSocketCoreImpl$sendMessage: Sending message 3313: {type=ping, id=3313}
11-18 12:57:03.763  2345 30471 D WebSocketCoreImpl$sendMessage: Message number 3313 sent awaiting answer from WebSocket
11-18 12:57:03.779  2345  2541 D WebSocketCoreImpl: Websocket: onMessage (text)
11-18 12:57:03.780  2345  2541 D WebSocketCoreImpl: Message id 3312 received
11-18 12:57:03.782  2345  2541 D WebSocketCoreImpl: Websocket: onMessage (text)
11-18 12:57:03.782  2345  2541 D WebSocketCoreImpl: Message id 3313 received
11-18 12:57:05.153  2345  2345 D NotificationManagerExtensionsKt: Cancel notification with tag "null" and id "0"
11-18 12:57:05.154  2345  2345 D NotificationManagerExtensionsKt: Check if the notification is in a group...
11-18 12:57:05.154  2345  2345 D NotificationManagerExtensionsKt: Notification is not in a group. Cancel notification...
11-18 12:57:05.195  2345 14365 D ServerConnectionInfo: usesVpn is: false
11-18 12:57:05.199  2345 14365 D ServerConnectionInfo: usesInternalSsid is: true, usesWifi is: true
11-18 12:57:05.242  2345 14365 D NotificationDeleteReceiver$onReceive: Notification cleared event successful!
11-18 12:57:05.673  2345  2345 D ImeBackDispatcher: switch root view (mImeCallbacks.size=0)
11-18 12:57:05.705  2345  2345 D InsetsController: hide(ime())
11-18 12:57:05.707  2345  2345 I ImeTracker: io.homeassistant.companion.android:18056f4a: onCancelled at PHASE_CLIENT_ALREADY_HIDDEN
11-18 12:57:05.709  2345  2345 D IntegrationRepositoryImpl: isAppLocked(): false. (LockEnabled: false, appActive: true, expireMillis: 1763492076957, currentMillis: 1763492225708)
11-18 12:57:05.730  2345  2345 D IntegrationRepositoryImpl: setAppActive(): true
11-18 12:57:06.227  2345 26347 D LogcatReader$readLog: Read logcat for pid 2345
```

**Screenshot or video of problem:**

**Additional information:**

### PR DESCRIPTION
**Pull request by marazmarci**
## Summary

Fixes #6066, where users were getting duplicate notifications over the persistent WebSocket connection. The bug was introduced in #5998, where the periodic WorkManager work request's unique name was renamed from `WebSockManager` to `WebSocketManager`. This change resulted in two periodic jobs, because the old one was still persisted, and scheduled to try to start every 15 minutes.

I used the `App Inspection` feature of Android Studio to see the list of WorkManager jobs, and I was able to capture this screenshot:

image

Here you can see two instances of `WebsocketManager` running at the bottom of the list. Unfortunately this tool cannot show the unique name of the jobs, but the fact that two of the same type are running should be enough proof.

## Checklist

- [ ] New or updated tests have been added to cover the changes following the testing [guidelines](https://developers.home-assistant.io/docs/android/testing/introduction).
- [x] The code follows the project's [code style](https://developers.home-assistant.io/docs/android/codestyle) and [best_practices](https://developers.home-assistant.io/docs/android/best_practices).
- [x] The changes have been thoroughly tested, and edge cases have been considered.
- [x] Changes are backward compatible whenever feasible. Any breaking changes are documented in the changelog for users and/or in the code for developers depending on the relevance.

### CODE REVIEW

**Review by TimoPtr — COMMENTED** [review]
Very nice finding! For clarity purpose please add documentation explaining why we do that and link it to your comment in the issue. Also this should be removed after some time from the codebase.

**Comment by marazmarci** [comment]
Thanks for the quick review, I added an explanation comment in 4cb2f69! Please check it out.

Do you have any reliable way to schedule a reminder to remove it, preferably so that every contributor gets a notification through GitHub? I was thinking about scheduling an email response to this thread in Gmail, which should add a comment here. And what do you think about let's say 1 year from now, to give enough time for everyone to update? Or is 1 year too long? Or from another perspective, is there anything that's hurrying us to remove it, except for the risk of forgetting (which a scheduled notification solves)?

**Comment by TimoPtr** [comment]
> Thanks for the quick review, I added an explanation comment in [4cb2f69](https://github.com/home-assistant/android/commit/4cb2f69c19d20e83f81b45243e2d21cd06e32db3)! Please check it out.
> 
> Do you have any reliable way to schedule a reminder to remove it, preferably so that every contributor gets a notification through GitHub? I was thinking about scheduling an email response to this thread in Gmail, which should add a comment here. And what do you think about let's say 1 year from now, to give enough time for everyone to update? Or is 1 year too long? Or from another perspective, is there anything that's hurrying us to remove it, except for the risk of forgetting (which a scheduled notification solves)?

We probably should create an issue with a due date. 1 year seems reasonable. Then in the code add a link to this issue. It's only important for anyone that might work on this code later and could remove it if doing some refactor or something instead of keeping the logic forever.

File: app/src/main/kotlin/io/homeassistant/companion/android/websocket/WebsocketManager.kt [hunk 1]
```diff
@@ -66,17 +67,23 @@ class WebsocketManager(appContext: Context, workerParams: WorkerParameters) :
                     .build()
 
             val workManager = WorkManager.getInstance(context)
-            val workInfo = workManager.getWorkInfosForUniqueWork(TAG).await().firstOrNull()
+
+            // This is needed because the unique work name had been renamed, and it caused two scheduled periodic workers to exist,
+            // and it resulted in duplicate notifications over WebSocket.
+            // https://github.com/home-assistant/android/issues/6066#issuecomment-3608649429
```
Comment (TimoPtr) [inline app/src/main/kotlin/io/homeassistant/companion/android/websocket/WebsocketManager.kt]:
```suggestion

            // Renaming the unique work name created two periodic workers and caused duplicate WebSocket notifications.
            // See: https://github.com/home-assistant/android/issues/6066#issuecomment-3608649429
            // Could be remove .........
```

Comment (marazmarci) [reply app/src/main/kotlin/io/homeassistant/companion/android/websocket/WebsocketManager.kt]: Thanks, it's much more concise than my version.

**Comment by marazmarci** [comment]
Nice, I didn't know GitHub allows you to set a due date on an issue!

To prevent accidental removal of the `cancelUniqueWork` call, I added a `Please don't remove before December 2026 to allow enough time for users to upgrade.` comment to the code!

**Review by TimoPtr — APPROVED** [review]
Thanks again 👍🏻

**Comment by TimoPtr** [comment]
> Nice, I didn't know GitHub allows you to set a due date on an issue!

I don't think it can but we can simply write it down in the issue. But don't worry let's keep it like this for now.
