### PR TITLE
Fix button widget authentication dismissed due to non-foreground window

### LINKED ISSUE #3893: Service Button Widgets Do Not Open Authentication Window On Android 14 QPR1+
**Home Assistant Android app version(s):**
2023.9.2-full

**Android version(s):**
U1B1.230908.003 (Android 14 QPR 1)

**Device model(s):**
Pixel Fold

**Home Assistant version:**
2023.9.3

**Last working Home Assistant release (if known):**
2023.9.2 (HAOS)
2023.9.2-full (Android)

**Description of problem, include YAML if issue is related to notifications:**
Android service button widgets that have authentication enabled no longer work on Android 14 QPR Beta 1. Clicking the widget does nothing, but spam clicking the widget may inconsistently bring up the authentication window. Disabling authentication allows the widget to work (albeit without authentication). Service button widgets with authentication did work on Android 14 Beta 5.3. Recreating the widget or restarting the device does not fix the issue.

**Companion App Logs:**
The last bit of the attached companion app log seems relevant. Widget authentication is cancelling before authentication pops up.
```
09-26 21:10:26.203  4534  4534 D ButtonWidget: Broadcast received: 
09-26 21:10:26.203  4534  4534 D ButtonWidget: Broadcast action: io.homeassistant.companion.android.widgets.button.ButtonWidget.CALL_SERVICE_AUTH
09-26 21:10:26.203  4534  4534 D ButtonWidget: AppWidgetId: 163
09-26 21:10:26.203  4534  4534 D ButtonWidget: Calling authentication, then configured service
09-26 21:10:26.237  4534  4534 D WidgetAuthenticationA: onCreate in WidgetAuthenticationActivity called
09-26 21:10:26.260  4534  4534 D Unlock  : onAuthenticationError -> 10 :: Authentication canceled
09-26 21:10:26.260  4534  4534 D WidgetAuthenticationA: Authentication canceled by user, closing activity
09-26 21:10:26.269  4534  4534 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=androidx.activity.OnBackPressedDispatcher$Api33Impl$$ExternalSyntheticLambda0@5b589b6
09-26 21:10:26.294  4534  4534 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.app.Activity$$ExternalSyntheticLambda0@b86b8d5
09-26 21:10:27.644  4534  4534 D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 1695777025122, currentMillis: 1695777027644)
09-26 21:10:27.668  4534  4534 W Choreographer: Frame time is 0.153961 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
09-26 21:10:27.698  4534  4534 D IntegrationRepository: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 1695777025122, currentMillis: 1695777027698)
09-26 21:10:27.698  4534  4534 D IntegrationRepository: setAppActive(): true
09-26 21:10:29.180  4534 21357 D LogcatReader: Read logcat for pid 4534
```
[homeassistant_companion_log_8-26-2023_21-10-37.txt](https://github.com/home-assistant/android/files/12733066/homeassistant_companion_log_8-26-2023_21-10-37.txt)

**Screenshot or video of problem:**

https://github.com/home-assistant/android/assets/43071698/b7c2ab62-ac3e-408c-bef3-0b0426c60980

**Additional information:**
This may be an issue with Android 14 QPR Beta 1 and a bug for it has also been created in the Google issue tracker: https://issuetracker.google.com/issues/302159855

### PR DESCRIPTION
**Pull request by jpelgrom**
## Summary

Fixes #3893: prevent the button widget authentication dialog automatically being dismissed when triggered on Android 14 QPR1+, because the window was not in the foreground. It looks like the framework check for this was bugged before QPR1, and the Home Assistant app was showing the authentication dialog before the window (which is transparent) was in the foreground.

More details about how I found this in my last comment on the issue.

## Screenshots

No visual changes except maybe you have to wait 50-100ms longer for the window to get to the foreground compared to older versions?

https://github.com/home-assistant/android/assets/8148535/d526e696-9a98-4a0a-9cfe-47f6bce48ae7

## Link to pull request in Documentation repository

n/a

### CODE REVIEW

File: app/src/main/java/io/homeassistant/companion/android/widgets/common/WidgetAuthenticationActivity.kt [hunk 1]
```diff
@@ -15,12 +15,20 @@ class WidgetAuthenticationActivity : AppCompatActivity() {
...
+    private var authenticating = false
+
     override fun onCreate(savedInstanceState: Bundle?) {
         super.onCreate(savedInstanceState)
         Log.d(TAG, "onCreate in WidgetAuthenticationActivity called")
+    }
 
-        val authenticator = Authenticator(this, this, ::authenticationResult)
-        authenticator.authenticate(getString(R.string.biometric_set_title))
+    override fun onWindowFocusChanged(hasFocus: Boolean) {
```
Comment (dshokouhi) [inline app/src/main/java/io/homeassistant/companion/android/widgets/common/WidgetAuthenticationActivity.kt:25]: should we consider adding a log statement here for consistency purposes in the file?

Comment (jpelgrom) [reply app/src/main/java/io/homeassistant/companion/android/widgets/common/WidgetAuthenticationActivity.kt:25]: That feels like a log statement you only use during debugging. If it was up to me, the one in `onCreate` is also unnecessary.

**Review by dshokouhi — APPROVED** [review]

**Review by JBassett — APPROVED** [review]
